### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Objective-Zero** [dogo/SCLAlertView#100]
Hi,

Just downloaded and implemented your library. Getting a EXC_BAD_ACCESS crash like shown in the attached image when tapping the dismiss button of an alert view. 
![screen shot 2015-04-12 at 3 21 30 am](https://cloud.githubusercontent.com/assets/1030802/7104728/22bc3fb6-e0c3-11e4-8995-a0a2350f9d39.png)

**Comment by dogo** [comment]
iOS version
Emulator or device?
Xcode version ?

**Comment by Objective-Zero** [comment]
iOS 8.1.2
Device
Xcode 6.3

**Comment by dogo** [comment]
It's running fine here, could you please post your source code please

**Comment by Objective-Zero** [comment]
SCLAlertView *alert = [[SCLAlertView alloc] init];
    [alert addButton:@"Email Developer" actionBlock:^(void) {
        SHKItem *mailItem = [SHKItem text:@""];
        [mailItem setMailToRecipients:[NSArray arrayWithObjects:@"myEmail@yahoo.com", nil]];
        [mailItem setTitle:@"App Inquiry"];
        [SHKMail shareItem:mailItem];
    }];
[alert showInfo:self title:@"Info" subTitle:@"You can rename the notes within the table by clicking the trash can icon." closeButtonTitle:@"Dismiss" duration:0.0f];

**Comment by Objective-Zero** [comment]
Sorry for not formatting the code there, still new to this site. But pretty much I just implemented the library, used that code and it crashed when clicking the dismiss button.

**Comment by dogo** [comment]
Hi, @Objective-Zero 

Your code seems fine, try to remove the SHK stuff and run again. Like this

``` Objetive-C
SCLAlertView *alert = [[SCLAlertView alloc] init];
[alert addButton:@"Email Developer" actionBlock:^(void) {
    NSLog(@"LOG"); 
}];
[alert showInfo:self title:@"Info" subTitle:@"You can rename the notes within the table by clicking the trash can icon." closeButtonTitle:@"Dismiss" duration:0.0f];
```

Probably its something related to SHK

**Comment by Objective-Zero** [comment]
The SHK stuff is not the problem. I just slightly altered the library code to make a button tap effect by changing the buttons alpha level and that worked so it must just be a bug that is hard to track down. I mean you can investigate this more if you would like but I am happy with my approach right now.

**Comment by Objective-Zero** [comment]
I found the issue! I was using the library in a non-ARC project so that bug resulted from not using ARC. Once I included the proper compiler flags it worked properly.
