### ISSUE TITLE
Enhancement: Support iOS 8 Widget frame position

### ISSUE THREAD

**Issue by Supertecnoboff** [dogo/SCLAlertView#102]
Hi,

This is just a simple enhancement that I thought of and is what I am using to correctly position the height of the SCLAlertView pop up in my iOS 8 Widget.

So when you are using the alert in an app, then it does not matter, you can just allow the library to use ```[UIScreen mainScreen].bounds.size;``` to get the size of the screen. However, when you are using a widget, you cannot use the screen size to figure out how to correctly position the alert. Therefore you need to manually pass in the height of the widget to SCLAlertView. Thus made these simple edits to get it to work nicely.

1) I added a height integer to be passed in when calling any one of the alert popup methods like so:

```
- (void)showSuccess:(UIViewController *)vc title:(NSString *)title subTitle:(NSString *)subTitle closeButtonTitle:(NSString *)closeButtonTitle duration:(NSTimeInterval)duration viewHeight:(int)height;
```

2) In SCLAlertView.h, I declared an integer that stores the height when passed in:

```
@interface SCLAlertView : UIViewController {
    int view_height;
}
```

3) In the SCLAlertView.m file in the ```viewWillLayoutSubviews``` method, I added this if statement to check the value of the integer called ```view_height```, if the value is 0, then SCLAlertView will use the screen bounds, otherwise it will use the value of ```view_height``` to correctly set the vertical position of the view. I did this like so:

```
// Check if we are using a Widget, if so then
// lets set the height manually.
if (view_height > 0) {
     sz.height = view_height;
}
```

**Comment by Supertecnoboff** [comment]
Also just one other thought, would it be possible to add a popup option which allows you to embed a custom view inside it, this would allow developers to be able to add things like pictures, videos, etc... Anything they want, then they could link those views to another class and add any kind of feature they want. I think it would be a pretty cool feature to add to the app. Because write now you can add certain features like text, buttons, titles.

**Comment by dogo** [comment]
Hi, @Supertecnoboff 

Could you please test my commit cb53c94

Yeah, some guys asked for this too (add custom view), I'm thinking about it

**Comment by Supertecnoboff** [comment]
@dogo Interesting, will try it out when I have time. One last question, do you guys plan on bringing this to the Mac? If so, I would LOVE to use it for my Mac apps. This is a superb alert, I tried to port it myself but failed miserably lol :)
