### ISSUE TITLE
XCode 6.3 Warning: roperty access is using 'setSubTitleHeight:' method which is deprecated

### ISSUE THREAD

**Issue by franklsf95** [dogo/SCLAlertView#105]
I received the following warnings in XCode 6.3 compilation:

    Pods/SCLAlertView-Objective-C/SCLAlertView/SCLAlertView.m:87:14: Property access is using 'setSubTitleHeight:' method which is deprecated
    Pods/SCLAlertView-Objective-C/SCLAlertView/SCLAlertView.m:758:22: Property access is using 'setSubTitleHeight:' method which is deprecated
    Pods/SCLAlertView-Objective-C/SCLAlertView/SCLAlertView.m:763:22: Property access is using 'setSubTitleHeight:' method which is deprecated
    Pods/SCLAlertView-Objective-C/SCLAlertView/SCLAlertView.m:774:22: Property access is using 'setSubTitleHeight:' method which is deprecated
    Pods/SCLAlertView-Objective-C/SCLAlertView/SCLAlertView.m:779:22: Property access is using 'setSubTitleHeight:' method which is deprecated
    Pods/SCLAlertView-Objective-C/SCLAlertView/SCLAlertView.m:787:14: Property access is using 'setSubTitleHeight:' method which is deprecated

The method declaration says:

    /** Set SubTitle Height
     *
     * @deprecated Deprecated since 0.5.2+ .
     * @param value Height of scrollable subtitle text field.
     */
    - (void)setSubTitleHeight:(CGFloat)value __deprecated;

What is the proper way to fix this?

**Comment by dogo** [comment]
It's already fixed, but a new version was not released

**Comment by franklsf95** [comment]
Do you have a timetable to release? Thank you.

**Comment by dogo** [comment]
Please update to 0.7.1

**Comment by franklsf95** [comment]
Thanks!

**Comment by rjcristy** [comment]
Not working again at version 1.1.2

**Comment by dogo** [comment]
Could you please provide me a sample. 

Thanks
