### ISSUE TITLE
Long text makes the alert larger than view.

### ISSUE THREAD

**Issue by alvarogirona** [dogo/SCLAlertView#107]
If the alert subTitle text is too large the alert height goes bigger than the device view.
![img_0003](https://cloud.githubusercontent.com/assets/929869/7250044/365ba986-e81f-11e4-8c21-acda9b82dbfd.jpg)

**Comment by dogo** [comment]
uhauhuahauahuahuaha! Thats a hugeee text :D. 
It's a bug but a bad behaviour too
