### ISSUE TITLE
Adding a countdown to a default button

### ISSUE THREAD

**Issue by kalsky** [dogo/SCLAlertView#113]
When you set the duration of the alert, it would be nice if we can show a timer on the default button (either the done button or any other button that the developer thinks should be the default).
It can work the same as implemented in Waze for most of their popups. 
Similar question was asked here, and a sample code is also attached:
http://stackoverflow.com/questions/11783439/uibutton-with-timer

I'll try to integrate it on my own and share it if i'll have time - but if not, it would be nice having this feature built in with this great project.

Yaniv

**Comment by dogo** [comment]
Ohhhh I really liked this! @kalsky 
Added to my TODO :dart:

**Comment by dogo** [comment]
@kalsky Feature provided by @yatryan

**Comment by kalsky** [comment]
Thanks for adding this!
But your countdown counts forward.. it's actually a timer..
I changed the code in the SCLTimerDisplay to:

- (void)updateTimerButton:(NSTimer *)timer{
    currentTime -= TIMER_STEP;
    currentAngle = (currentTime/timerLimit) * 360 + START_DEGREE_OFFSET;
    
    if(currentTime<=0) {
        [self stopTimer];
    }
}

and in the startTimerWithTimeLimit, I set the currentTime to tl as well.

**Comment by dogo** [comment]
ahhahaha thats true! Fixed now, supports countdown and timer :D
