### ISSUE TITLE
Unable to move alertView so keyboard covers the fields on the alert.

### ISSUE THREAD

**Issue by xeppen** [dogo/SCLAlertView#118]
I am trying to add 3 textfields on the alert but on smaller devices the keyboard covers the fields so you can't see what you write. I would like a feature to move the textfield up if needed.

**Comment by alexcosmin** [comment]
Try using this component https://github.com/hackiftekhar/IQKeyboardManager .
I didn't try to use it with textfields inside a SCLAlertView, but works as a charm with textfields in a regular UIView.

**Comment by dogo** [comment]
Yep, I'ts a know issue
