### ISSUE TITLE
UITextField Return/Done Action (UIControlEventEditingDidEndOnExit)

### ISSUE THREAD

**Issue by batnom** [dogo/SCLAlertView#123]
It seems the default action of when the 'Done' button is to just hide the keyboard, but it would be ideal if it can hit the same action as the button you add with the Text Field.

Though adding the target to the text field doesn't work.  

I've tried making it work a few different ways but it doesn't seem to stick.

```
    __weak UITextField *weakField = [alert addTextField:@"enter keyword here"];
    [weakField addTarget:self action:@selector(keywordSearch) forControlEvents:UIControlEventEditingDidEndOnExit];
```

```
    UITextField *textField = [alert addTextField:@"enter keyword here"];
    [textField addTarget:self action:@selector(keywordSearch) forControlEvents:UIControlEventEditingDidEndOnExit];
```

```
    UITextField *textField = [alert addTextField:@"enter keyword here"];
    openTextField = textField;
    [openTextField addTarget:self action:@selector(keywordSearch) forControlEvents:UIControlEventEditingDidEndOnExit];
```

But the `keywordSearch` function is never called.

Any suggestions?

**Comment by glennposadas** [comment]
hi @batnom , how about trying to do what you want to do inside the textField delegate (**textFieldShouldReturn**) ? 

`// MARK: - TextField Delegate

extension LoginViewController {
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        
        if textField == textField_Email{
            textField_Password.becomeFirstResponder()
        } else if textField == textField_Password {
            self.action_Login(self)
        } else {
            // SCAlertView
            if textField.tag == ViewConstants.forgotPasswordTextFieldTag {
                if let alertView = self.childViewControllers.first as? SCLAlertView  {
                    alertView.dismiss(animated: true, completion: {
                        // dismiss alert then proceed to forgot password.
                        print("done dismissing")
                    })
                }
            }
        }
        
        return true
    }
    
}
`

**Comment by dogo** [comment]
Please fill the issue template
