### ISSUE TITLE
previous alert won't go away if new 1 appears

### ISSUE THREAD

**Issue by Waderoni** [dogo/SCLAlertView#124]
Hi. I'm using this in conjunction with a barcode scanner.  This works very fast and if there's a error, I present a "notice" SCLAlertView for 2 seconds but if the user gets moving too fast, they might get 2 errors quickly.  When this happens, 2 SCLAlertViews will pop up.  The last 1 produced will animate away fine but the 1 that was previously produced will not actually animate away and will be stuck on screen forever. 

Have you seen this issue before?

**Comment by dogo** [comment]
This issue is related to your application, maybe if you check "isVisible" before show the alert

**Comment by Waderoni** [comment]
good call.  Ok cool.  
Thanks. I’ll put the check in

-Wade
