### ISSUE TITLE
Alertview without the round circle above.

### ISSUE THREAD

**Issue by lupugabriel** [dogo/SCLAlertView#125]
i would like to use the alertview without the round circle on the top. Is this possible?

Thanks

**Comment by lupugabriel** [comment]
ok. i found the removeTopCircle method.
Can i add a picture under the title?
or the title changed to a picture?

**Comment by lupugabriel** [comment]
What i want to achieve and what i achieved using:

UIImageView *view = [[UIImageView alloc] initWithFrame:CGRectMake(self.view.frame.size.width/2 -120, self.view.frame.size.height/2 - 178, 240, 50)];
    [view setImage:[UIImage imageNamed:@"alertViewBacgtround_rate"]];
    [alertView.view addSubview:view];

![screen shot 2015-06-12 at 12 03 59](https://cloud.githubusercontent.com/assets/3657507/8128870/2e74b73a-10fb-11e5-965c-80ffafd760ac.png)
![screen shot 2015-06-12 at 12 04 07](https://cloud.githubusercontent.com/assets/3657507/8128871/2e7a4e52-10fb-11e5-8158-c903a3c36099.png)

**Comment by lupugabriel** [comment]
ok... i can add it to alertview.titleLabel... now i saw it... sorry for the post!

**Comment by dogo** [comment]
no problem :D
