### ISSUE TITLE
How to change default button label?

### ISSUE THREAD

**Issue by mehmetvefa** [dogo/SCLAlertView#128]
How can I change default button text? I am using default alert and I have a **DONE** button.

```
let alertview : SCLAlertViewResponder = SCLAlertView().showError( "Hata!", subTitle: "Lütfen bilgilerinizi kontrol edin." )
```

I want to change this button text without add any more button.

**Comment by dogo** [comment]
@mehmetvefa Wrong lib, this is the Objective-C version.

**Comment by mehmetvefa** [comment]
So which one is true?

**Comment by dogo** [comment]
https://github.com/vikmeup/SCLAlertView-Swift   Swift version
