### ISSUE TITLE
adding more control method

### ISSUE THREAD

**Issue by RockyAo** [dogo/SCLAlertView#130]
could you add a method for dismiss ..   it  will auto dismiss  .  but I want it do something like send a request. when it success  then dismiss ..so please add a method to control  it.by the way  thanks for your Library..  it s really cool

**Comment by dogo** [comment]
humm, you can send your request and if success or failure call ```hideView``` something like:

```
Send request ->
      success:
             [alert hideView];
      failure:
             Do whatever you want

**Comment by RockyAo** [comment]
ok,, my fault  ,I  didn't see that method..   I had already add another method to your library  ,to controll that . thank u.
