### ISSUE TITLE
Subtitle issue not showing properly - urgent

### ISSUE THREAD

**Issue by raheelahmad786** [dogo/SCLAlertView#131]
Subtitle not showing properly as it is cutting "Y" and "G" characters at bottom.
<img width="254" alt="screen shot 2015-07-09 at 1 07 22 pm" src="https://cloud.githubusercontent.com/assets/7985860/8590607/8aea984a-263b-11e5-92ed-e716e9012f40.png">

**Comment by chadpod** [comment]
I ran into this one as well. Until it is fixed, I just added the following to the initialization of _viewText.

_viewText.clipsToBounds = NO;

**Comment by raheelahmad786** [comment]
Fixed now.

**Comment by dogo** [comment]
Fixed properly
