### ISSUE TITLE
I can't see the added button

### ISSUE THREAD

**Issue by Piero87** [dogo/SCLAlertView#132]
hi, i have a problem with the SCLAlertView, i can't see the adde button, this i my code:

        SCLAlertView *alert2 = [[SCLAlertView alloc] initWithNewWindow];
        [alert2 showSuccess:self title:@"Button View" subTitle:@"This alert view has buttons" closeButtonTitle:nil duration:0.0f];
        [alert2 addButton:@"First Button" target:self selector:@selector(close_view:)];

and this what i see:
![schermata 2015-07-16 alle 00 20 18](https://cloud.githubusercontent.com/assets/768952/8711255/a0f6d292-2b50-11e5-8e0a-65716dbacf8b.png)

if i press in the blank space, the button works, but i can't see it, i have wrong something?

**Comment by dogo** [comment]
Hi @Piero87 , thats simple :D, you need to add the button before the alert is displayed like this

```
Objective-c
SCLAlertView *alert2 = [[SCLAlertView alloc] initWithNewWindow];
    [alert2 addButton:@"First Button" target:self selector:@selector(close_view:)];
    [alert2 showSuccess:self title:@"Button View" subTitle:@"This alert view has buttons" closeButtonTitle:nil duration:0.0f];
```

**Comment by Piero87** [comment]
I feel stupid! Thanks!
