### ISSUE TITLE
Parenthesis missing in SCLAlertView.m

### ISSUE THREAD

**Issue by LeandroHub** [dogo/SCLAlertView#133]
When integrating SCLAlertView via Cocoa Pods, I got an error in SCLAlertView.m:212. The line says:

> if UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation])

but it should says:

> if (UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation]))

Does it happen to everyone? I've using GitHub since a couple of years but never collaborated to a project. Now I'm learning GIT and would like to collaborate. May I modify this issue and make a pull request?

Thanks!

**Comment by dogo** [comment]
Update your version , run pod update

**Comment by LeandroHub** [comment]
Thanks for answering. My pod file says:

> pod 'SCLAlertView-Objective-C'

After running pod install, shouldn't it download the latest version?

**Comment by dogo** [comment]
yep, 0.7.3 is the latest

**Comment by LeandroHub** [comment]
That's the problem... pod install update my copy to version 0.5.4. I should definitely run pod update. Sorry, I'm kind of new to Cocoa Pods too. Thanks!
