### ISSUE TITLE
Prepopulate alertview

### ISSUE THREAD

**Issue by WillemPieterse** [dogo/SCLAlertView#138]
Good Day,
Is it possible to pre-populate a textbox with a value?

Thanks for the Brilliant control! I am using it with Swift, because your implementtation is just so much better that the other one :)

**Comment by dogo** [comment]
Thank you @WillemPieterse 
humm, you want something like this ?

```
    SCLAlertView *alert = [[SCLAlertView alloc] init];
    
    UITextField *textField = [alert addTextField:@"Enter your name"];
    
    [alert addButton:@"Show Name" actionBlock:^(void) {
        NSLog(@"Text value: %@", textField.text);
    }];
    
    [alert showEdit:self title:kInfoTitle subTitle:kSubtitle closeButtonTitle:kButtonTitle duration:0.0f];
```
![ios simulator screen shot aug 18 2015 10 20 07 am](https://cloud.githubusercontent.com/assets/1487375/9330912/b6f17578-4592-11e5-834c-b87f702f8675.png)
