### ISSUE TITLE
Get rid of the icon

### ISSUE THREAD

**Issue by jdgong** [dogo/SCLAlertView#147]
Hi 

Is there a way to get rid of the icon, with just the text box (possibly with some buttons)? 

Thanks!

**Comment by dogo** [comment]
```
/** Remove Top Circle
 *
 * Remove top circle from SCLAlertView.
 */
- (void)removeTopCircle;
```

use this before show

**Comment by alejandroivan** [comment]
Hi @dogo !
Continuing this question, when removing the top circle, how do you get rid of the space used by it?
I just removed the top circle for an alert but there's a lot of empty space on top of the title that I can't get rid off. Any suggestions?

Thanks!

**Comment by jerry317** [comment]
@dogo I also want to know how to remove the empty space of top icon. Thanks

**Comment by dogo** [comment]
Currently there is no way to remove the space. Sorry guys

**Comment by tinpont** [comment]
+1 for remove icon space.

**Comment by rurza** [comment]
@dogo it seems, that there is hardcoded value of top margin. What if I change it?
