### ISSUE TITLE
SCLAlertView is not working!!!!!!!

### ISSUE THREAD

**Issue by JackZYH** [dogo/SCLAlertView#148]
// When I user SCLAlertView like this, is not working!  And what should I do?

SCLAlertView *alert = [[SCLAlertView alloc] init];
        [alert showWarning:@"xxxx" subTitle:@"xxxx" closeButtonTitle:@"xxxx" duration:0.0f];
        [alert addButton:@"xxxx" actionBlock:^{
           // xxxx
        }];

**Comment by lajosdavid** [comment]
You have to set the view controller the alert view will be displayed in.
```obj-c
SCLAlertView *alert = [[SCLAlertView alloc] init];
[alert showWarning:viewController title:@"Title" subTitle:@"SubTitle" closeButtonTitle:@"Close" duration:0.f];
```

Or if you want to present it in a new window, use this:
```obj-c
SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];
[alert showWarning:@"Title" subTitle:@"SubTitle" closeButtonTitle:@"Close" duration:0.f];
```

**Comment by dogo** [comment]
Thanks @lajosdavid
