### ISSUE TITLE
iPad pro split screen support

### ISSUE THREAD

**Issue by haoatvapormedia** [dogo/SCLAlertView#149]
Hi Guys,

Just testing out SCLAlertView on iPad pro split screen, it seems like the alert is going to pop up at screen centre rather than the centre of the application.

Details can be found on the below screenshot.

![simulator screen shot 28 oct 2015 4 02 25 pm](https://cloud.githubusercontent.com/assets/14046249/10780097/c721efa8-7d8d-11e5-9eb0-c3853dc36555.png)

Tips: To enable split screen mode on iPad pro, slide from right hand side of the edge, and then drag the split bar

Cheers,

H

**Comment by dogo** [comment]
Ops, bug :D

I'm currently busy with another project and I can't get any any ETA to fix this. Sorry 

But you can also fix by yourself and make a PR

**Comment by abbasmousavi** [comment]
@dogo I think that https://github.com/dogo/SCLAlertView/pull/153 will fix this. Please accept this PR.

**Comment by dogo** [comment]
@haoatvapormedia @abbasmousavi fixed could you please test the develop branch
