### ISSUE TITLE
How do I add SCLAlertView to TheOs project?

### ISSUE THREAD

**Issue by iZ3ro** [dogo/SCLAlertView#151]
Hello I want to add SCLAlertView using Theos on my iPhone? How? Where do I put the files etc.. Help please. Thanks in advance!

**Comment by dogo** [comment]
What is TheOS?

**Comment by iZ3ro** [comment]
@dogo http://iphonedevwiki.net/index.php/Theos

**Comment by dogo** [comment]
hum! Thats pretty cool but at the moment I got no time to look into

**Comment by dogo** [comment]
Fell free to make a PR or add more information about it
