### ISSUE TITLE
keyboard bug

### ISSUE THREAD

**Issue by abc19abc91** [dogo/SCLAlertView#155]
![image](https://cloud.githubusercontent.com/assets/5125983/11451771/a59317b2-960c-11e5-805c-50c147f19eb9.png)

let alert = SCLAlertView()
		let txt = alert.addTextField("Enter your name")
        alert.addTextField("Enter your pwd")
		alert.addButton("Show Name") {
			print("Text value: \(txt.text)")
		}
		alert.showEdit(kInfoTitle, subTitle:kSubtitle)

add two textfield,switch focus ,  bug...

**Comment by abc19abc91** [comment]
![image](https://cloud.githubusercontent.com/assets/5125983/11452614/846c6986-9629-11e5-8e98-09b08e06df09.png)

add some code, not completed solve problem

**Comment by 942v** [comment]
Why you don't use the swift version?

**Comment by dogo** [comment]
What? Are you using the Swift or the Object-C version ?

**Comment by 942v** [comment]
I think so because the code in the SS is in swift. He should be using the swift version and not bridging the Objective-C version.

**Comment by abc19abc91** [comment]
![image](https://cloud.githubusercontent.com/assets/5125983/11618825/dc398c72-9cda-11e5-9530-29a346e35b57.png)
my project is swift,using ss Swift

**Comment by abc19abc91** [comment]
![image](https://cloud.githubusercontent.com/assets/5125983/11619134/2d5d1ade-9cdf-11e5-9e0e-f2e6c710228a.png)
using sample project, only add one more edit, switch focus,then bug...

**Comment by dogo** [comment]
Wrong project, this one is the objetive-c version
