### ISSUE TITLE
Multitasking Split Screen Bug

### ISSUE THREAD

**Issue by 942v** [dogo/SCLAlertView#158]
The Alert appears at the middle of the UIScreen always, even if the UIWindow is smaller (like when you use iOS 9 multitasking split screen). I'm going to try to fix it, any hint?

**Comment by dogo** [comment]
hum, I'm not tested yet the multitasking split screen support So the support is unknown.
Maybe the PR #153 could give you some information.

Thanks in the advance

**Comment by dogo** [comment]
Please update to 0.8.0
