### ISSUE TITLE
pop-up from pop-up enhancement

### ISSUE THREAD

**Issue by wdcurry** [dogo/SCLAlertView#162]
An ideal solution to a pop-up that could involve complicated details would be to have the ability to tap a "?" or similar button that _does NOT_ close down the originating popup but instead leaves it behind the informational popup. This can allow us to present a streamlined workflow, but still provide details to help confused users.

**Comment by wdcurry** [comment]
I have coded this in as another type of regular button, but a separate "over in the corner" kinda thing would be more appropriate. When i find time, i will package up the minor edits required in case others are interested.

**Comment by dogo** [comment]
:D. Sure take your time, I'm waiting
