### ISSUE TITLE
No Subtitle visible with iOS8.1

### ISSUE THREAD

**Issue by jusefjames** [dogo/SCLAlertView#164]
The Subtitle is not visible when running at iOS8.1 (Tested with Example Project and iOS 8.1 Simulator).

![simulator screen shot 28 12 2015 11 06 50](https://cloud.githubusercontent.com/assets/1645220/12017483/88eb6bc0-ad57-11e5-8bef-0062809378f8.png)

Line 823 in SCLAlertView.m:
`r = [str boundingRectWithSize:sz options:options attributes:attr context:nil];`
All values of r are 0 in iOS8.1 Simulator but are correct with iOS9.2 Simulator.
I will make a pull request on develop branch with this solution:
`CGSize size = [_viewText sizeThatFits:sz];` instead of `[str boundingRectWithSize:...]`
All examples are working with iOS8.1 and iOS9.2.

What do you think? Is there anything against `[_viewText sizeThatFits:sz]`?

**Comment by dogo** [comment]
Please update to 0.8.0
