### ISSUE TITLE
title width enhancement?

### ISSUE THREAD

**Issue by wdcurry** [dogo/SCLAlertView#166]
I generally try to avoid settings frames as much as possible, and given we set the title in the show method, it seems a tad more difficult to increase the size of the alert to match a slightly wider title. Cut-off titles just aren't proper.

Short of digging into the repo and editing, is there another way to manage this other than shortening the title itself?

**Comment by dogo** [comment]
```` Objective-C
/** Initialize SCLAlertView using a new window.
 *
 * Init with new window with custom width
 */
- (instancetype)initWithNewWindowWidth:(CGFloat)windowWidth;
``` 

You can increase the window width, making more room to your title
