### ISSUE TITLE
buttons from previous alertViews being displayed 

### ISSUE THREAD

**Issue by Jackson0111** [dogo/SCLAlertView#167]
Every time I call setupAlert() which sets up an alert view, buttons/textfield from previous alertViews will be added again and displayed. Here is the function: 

```
let alert = SCLAlertView()

func setupAlert() {

    alert.backgroundType = SCLAlertViewBackground.Blur

    alert.showAnimationType = SCLAlertViewShowAnimation.SlideInFromTop

    alert.hideAnimationType = SCLAlertViewHideAnimation.SlideOutToBottom

    alert.showInfo(self, title: "Notice", subTitle: "Share this app!", closeButtonTitle: "OK", duration: 0.0)

}

func test() {

      setupAlert() // if gets called 3 times, will have 3 ok buttons 
}
```

if I display this alert n times, there will be n "OK" buttons. Is there a way to fix this? But other than this, im loving this library, great work and I appreciate it!

**Comment by ridvank** [comment]
I have the same issue. Did you find a solution?

**Comment by Jackson0111** [comment]
I think putting let alert = SCLAlertView() inside of the function will fix the problem because it will just have a new instance of SCLAlertView every time the function gets called. Let me know if that works for you

**Comment by ridvank** [comment]
Nope it does not work actually. It does not create an single instance still.

**Comment by JeffMv** [comment]
Just to ensure you made it correctly, you must put `let alert = SCLAlertView()` at the beginning of the function. Hence, the code would look like

    func setupAlert() {
            // creates an instance
        let alert = SCLAlertView() 
    
            // Then the setup calls
        alert.backgroundType = SCLAlertViewBackground.Blur
        // ...
        alert.showInfo( ... )
    }

**Comment by ridvank** [comment]
The problem is when you create an instance of SCLAlertView when you dispatch a notification and create an instance after that.
