### ISSUE TITLE
Orientation issue in landscape when UIViewcontroller lock orientation in Portrait

### ISSUE THREAD

**Issue by ElDouD** [dogo/SCLAlertView#168]
I use SCLAlertView in an uiviewcontroller locking orientation by overriding these methods:

```
#pragma mark - Orientation configuration

- (BOOL) shouldAutorotate{
    return NO;
}

- (UIInterfaceOrientationMask) supportedInterfaceOrientations{
    return UIInterfaceOrientationMaskPortrait;
}
```

When the device is in landscape, my UI is still in portrait but the SCLAlertView is in landscape.
Is it possible to lock the orientation?

**Comment by kientux** [comment]
Though this issue is old, I find a way to fix this. I noticed that `SCLAlertView` is just a subclass of `UIViewController`, so I create my own subclass of `SCLAlertView` and override those orientation methods, and it works perfectly.

**Comment by ElDouD** [comment]
Thanks it works ;-)
