### ISSUE TITLE
when iOS8，use 

### ISSUE THREAD

**Issue by Easyzhan** [dogo/SCLAlertView#172]
[alert showNotice:self title:@"Notice" subTitle:@"test" closeButtonTitle:@"朕知道了" duration:0.0f];

subTitle can't be see

**Comment by dogo** [comment]
SCLAlertView version and device ?

**Comment by Easyzhan** [comment]
sorry，is Old version，“Fix for #164 no Subtitle with iOS8”，i saw it。 thx
