### ISSUE TITLE
Button actionBlocks not working

### ISSUE THREAD

**Issue by douglasg** [dogo/SCLAlertView#175]
[self hideView] in buttonTapped is setting btn.actionBlock and selector to nil but it should be called after button actions are done and not before.

SCAlertView.m:

- (void)buttonTapped:(SCLButton *)btn
{
    // Cancel Countdown timer
    [buttonTimer cancelTimer];
    
    // If the button has a validation block, and the validation block returns NO, validation
    // failed, so we should bail.
    if (btn.validationBlock && !btn.validationBlock()) {
        return;
    }
    if([self isVisible])
    {
        [self hideView];
    }

    if (btn.actionType == SCLBlock)
    {
        if (btn.actionBlock)
            btn.actionBlock();
    }
    else if (btn.actionType == SCLSelector)
    {
        UIControl *ctrl = [[UIControl alloc] init];
        [ctrl sendAction:btn.selector to:btn.target forEvent:nil];
    }
    else
    {
        NSLog(@"Unknown action type for button");
    }
}

Should be:

- (void)buttonTapped:(SCLButton *)btn
{
    // Cancel Countdown timer
    [buttonTimer cancelTimer];
    
    // If the button has a validation block, and the validation block returns NO, validation
    // failed, so we should bail.
    if (btn.validationBlock && !btn.validationBlock()) {
        return;
    }
    if (btn.actionType == SCLBlock)
    {
        if (btn.actionBlock)
            btn.actionBlock();
    }
    else if (btn.actionType == SCLSelector)
    {
        UIControl *ctrl = [[UIControl alloc] init];
        [ctrl sendAction:btn.selector to:btn.target forEvent:nil];
    }
    else
    {
        NSLog(@"Unknown action type for button");
    }
   if([self isVisible])
    {
        [self hideView];
    }
}

**Comment by innovative1** [comment]
Looks like this is a new issue with the latest release. I'm seeing the same thing after updating my pods

**Comment by innovative1** [comment]
This is the culprit: When the action block is registered, SCLAlertVIew registers a selection for the touch event.

```
    btn.actionBlock = action;
    [btn addTarget:self action:@selector(buttonTapped:) forControlEvents:UIControlEventTouchUpInside];
```
Then buttonTapped does this:
```- (void)buttonTapped:(SCLButton *)btn
{
    // Cancel Countdown timer
    [buttonTimer cancelTimer];
    
    // If the button has a validation block, and the validation block returns NO, validation
    // failed, so we should bail.
    if (btn.validationBlock && !btn.validationBlock()) {
        return;
    }
    if([self isVisible])
    {
        [self hideView];  // HideView is called before action block is.
    }

    if (btn.actionType == SCLBlock)
    {
        if (btn.actionBlock)
            btn.actionBlock();
    }
    else if (btn.actionType == SCLSelector)
    {
        UIControl *ctrl = [[UIControl alloc] init];
        [ctrl sendAction:btn.selector to:btn.target forEvent:nil];
    }
    else
    {
        NSLog(@"Unknown action type for button");
    }
}
```

Notice hideView is called before the action block. And Guess what hideView does:
```
- (void)hideView
{
 ....
    for (SCLButton *btn in _buttons)
    {
        btn.actionBlock = nil;
        btn.target = nil;
        btn.selector = nil;
    }
}
```

So the actionBlock is nil by the time it gets called in buttonTapped.

**Comment by dogo** [comment]
ops! my bad :P

**Comment by dogo** [comment]
Please update to 0.8.2
