### ISSUE TITLE
If new alert is displayed before 1st waiting alert is closed by duration, then 1st alert will never automatically close

### ISSUE THREAD

**Issue by Apptation** [dogo/SCLAlertView#178]
1st alert set to automatically close after duration of 3s:  
SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];
        alert.showAnimationType = FadeIn;
        alert.hideAnimationType = FadeOut;
        alert.shouldDismissOnTapOutside = YES;
        [alert showWaiting:@"First Alert ..." subTitle:@"blah blah blah ..." closeButtonTitle:nil duration:3.0f];

2nd alert called shortly after:
                        SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];
                        alert.showAnimationType = FadeIn;
                        alert.hideAnimationType = FadeOut;
                        alert.shouldDismissOnTapOutside = YES;
                        [alert showInfo:@"second alert" subTitle:@"Blah blah blah blah." closeButtonTitle:@"OK" duration:3.0f];

Second alert will close as expected after 3s, then first alert will just continue spinning until manually closed with a tap. Tried running each alert in a dispatch_async(dispatch_get_main_queue(), ^{ });

But that made no difference.

Any suggestions?

Thanks,

Chris

**Comment by dogo** [comment]
Please fill the issue template
