### ISSUE TITLE
Without SubTitle?

### ISSUE THREAD

**Issue by jnordh** [dogo/SCLAlertView#18]
Hello,
great AlertView! I am just implementing it in my Apps! However, I would like to show alert sometimes without SubTitle. How can I do it, without leaving a large space between Title and the button? To avoid the wasted space, would be great if this can be done/enhanced!
Many Thanks and regards
-Jan

**Comment by dogo** [comment]
@jnordh Please update to 0.5.0
Changelog
```Resize automatically alert view when the title or the subtitle is nil```
