### ISSUE TITLE
ButtonTimer: Enable button once timer elapsed

### ISSUE THREAD

**Issue by skuske** [dogo/SCLAlertView#181]
This is an enhancement request: add a new 'ButtonTimer' method, call it 'EnableButtonTimer' and enable a disabled button once the timer elapsed.

**Comment by dogo** [comment]
Sounds nice, but @skuske could you please give me more information about the desired behaviour

**Comment by skuske** [comment]
What I mean is: the dismiss button should be disabled by default, and after a timer has elapsed, the button should be enabled. Maybe the button's text should display a countdown if the seconds left before the button gets enabled.

**Comment by fabersky** [comment]
Agree!
Or, it could be:

`[alert addCancelButton:@"Close" actionBlock:^(void) {
    //);
}];`

**Comment by dogo** [comment]
Please fill the issue template
