### ISSUE TITLE
Vertical spacing broken on 0.9.0

### ISSUE THREAD

**Issue by chadpod** [dogo/SCLAlertView#183]
Just updated to 0.9.0 from 0.8.2 and vertical spacing between circle, text view, and buttons is broken. The text in the text view ends up underneath the button.

**Comment by dogo** [comment]
Could you please post a screenshot.
Thanks

**Comment by chadpod** [comment]
![img_6587](https://cloud.githubusercontent.com/assets/587627/12989467/d21c7f80-d0a9-11e5-84e1-19c9839de6ad.PNG)
0.8.2

versus

![img_6588](https://cloud.githubusercontent.com/assets/587627/12989471/d8570852-d0a9-11e5-841c-95c063acc1ec.PNG)
0.90

Guessing it has something to do with bounding rect not being computed properly for NSAttributedString in 0.9.0.

**Comment by chadpod** [comment]
Whoops didn't mean to close it, sorry.

**Comment by chadpod** [comment]
The bug is triggered by having a nil _labelTitle.text. The offending line appears to be:

```
_viewText.frame = CGRectMake(12.0f,  kTitleTop + _labelTitle.frame.size.height, _windowWidth - 24.0f, _subTitleHeight);
```

in viewWillLayoutSubviews

With a small adjustment, it seems to clear it up:

```
CGFloat y = (_labelTitle.text == nil) ? kTitleTop : kTitleTop + _labelTitle.frame.size.height;
_viewText.frame = CGRectMake(12.0f,  y, _windowWidth - 24.0f, _subTitleHeight);
```

**Comment by dogo** [comment]
yep ! @chadpod you are right, I was taking a look yesterday and I stumbled with the same line.
I will release asap a new version fixing this issue. 
Thank you

**Comment by dogo** [comment]
@chadpod Please update to 0.9.1
