### ISSUE TITLE
How to replace the latest SCLAlertView?

### ISSUE THREAD

**Issue by hdoria** [dogo/SCLAlertView#187]
Hi,

I'm running the following code:

``` obj-c
SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];
[alert showWaiting:@"Loading" subTitle:@"Please, wait" closeButtonTitle:nil duration:0.0f];
```

Is there a way to hide this alert automatically when I present a new one?

``` obj-c
SCLAlertView *errorAlert = [[SCLAlertView alloc] initWithNewWindow];
[errorAlert showError:@"Error" subTitle:@"...." closeButtonTitle:@"Close" duration:0.0f];
```

Would be great if initWithNewWindow could hide the latest alert automatically.  For now, I have to call hideView all the times.

**Comment by jbhav24** [comment]
I am having in the same situation and have been trying to solve it. How are you doing hideView? I also agree that initwithnewWindow should hide the previous alert.

**Comment by hdoria** [comment]
@vladdaneliuc I need to use initWithNewWindow

**Comment by matdimar** [comment]
When I call hideView before calling the second popup from the first one, XCode warns me that, "Capturing alert strongly in this block is likely to lead to a retain cycle." No issues seem to occur though.  Have you found any issues from the retain cycle that I may not have encountered yet? @hdoria @jbhav24
