### ISSUE TITLE
Alerts all placed on top of the nav bar

### ISSUE THREAD

**Issue by TECatFD** [dogo/SCLAlertView#196]
I have done a pod update of the Objective-C version today and all alerts are now popping up on top of the nav bar instead of the center of the window. The OK button does not respond, either.
![simulator screen shot 8 mar 2016 16 00 13](https://cloud.githubusercontent.com/assets/17114062/13607236/23b7c370-e547-11e5-8a19-4a66f639fe25.png)

**Comment by dogo** [comment]
could you please post your SCLAlertView code and what was your previous version?
