### ISSUE TITLE
Execute block while 'showWaiting' running

### ISSUE THREAD

**Issue by invisible66** [dogo/SCLAlertView#197]
I have a confirmation alert. when user press the 'Confirm' button i execute a block, hide this alert and call another method. Then showing waiting alert. i want to execute a block when waiting alert is shown. how can i do that?

Edit : 

i wrote this code. it's working but i didn't like that.. Is there another way?

      -(void)sendForm{

         SCLAlertViewBuilder *builder = [[SCLAlertViewBuilder alloc] initWithNewWindow]
         .addButtonWithActionBlock(@"Yes", ^{
             [self sendData];
         });

         SCLAlertViewShowBuilder *showBuilder = [SCLAlertViewShowBuilder new]
         .style(Warning)
         .title(@"User Informations")
         .subTitle(@"Informations will be updated. Continue?")
         .closeButtonTitle(@"No")
         .duration(0);
         [showBuilder showAlertView:builder.alertView onViewController:self];
     }

     -(void) sendData{
        SCLAlertView *alertXx = [[SCLAlertView alloc] init];
         [alertXx showWaiting:self title:LutfenBekle subTitle:@"Updating Informations.." closeButtonTitle:nil duration:0.0f];
         dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
            // accessing the server..
             dispatch_async(dispatch_get_main_queue(), ^{
                 [alertXx hideView];
             });
         });
     }

**Comment by LeandroHub** [comment]
I think it's a good approach! 

Anyway, I should set:

```__weak typeof(SCLAlertView) *weakAlert = alertXx;```

and use it inside the second dispatch_async like this:

```[weakAlert hideView];```
