### ISSUE TITLE
Position not always correct

### ISSUE THREAD

**Issue by enderoe** [dogo/SCLAlertView#20]
Hi,

I got to say that i love SCLAlertView! I have ran into one problem though: 
On some views the alert does not show up in the center of the view (see this screenshot: https://drive.google.com/a/socialbrothers.nl/file/d/0B6NlCTs3hnXlems4c1dueE9vMDA/view?usp=sharing )

Any thoughts on how to correct the position? 

Oh i call in the Custom AlertView from a UIBarbuttonItem to add a object to the users calendar (nothing strange)

**Comment by 3xtc** [comment]
Hey dogo sorry for comment here , how do I get alert.soundURL = [NSURL fileURLWithPath:[NSString stringWithFormat:@"%@/right_answer.mp3", [[NSBundle mainBundle] resourcePath]]];

To work ? I can share my code if can help please , is it so well popup is shown music will play ? Good feature I want if so .
