### ISSUE TITLE
[Bug] when changing keyboard...

### ISSUE THREAD

**Issue by iiMshl** [dogo/SCLAlertView#200]
when I'm in the textfield and change the keyboard to the emojis the alert goes down!.. # #

**Comment by fricred** [comment]
Is a issue  with 'initWithNewWindow' y solve using  'init' instead

**Comment by dogo** [comment]
Could not reproduce. Please give me some steps to reproduce

**Comment by iiMshl** [comment]
@fricred I don't get what you trying to say?
////
@dogo It's just when an alert is showing with a textfield while typing if I changed the language to anything else like from En to Emoji keyboard the alert moves down so I can't see the buttons and if I changed it one more time the alert just goes off the screen and there is just the black background for the alert...

**Comment by fricred** [comment]
Yes, I know. I have the same bug, but mi problem was I add a picker subview to a 5 input text, so every time that I focus an input, the alert goes down and down, so I realize that only ocurr when I instanse the alert how new window (initWithNewWindow) so I let the default (init) method and work very well. (sorry no bad English, I hope I understand me, when I get home I ll paste the code)

**Comment by dogo** [comment]
Please fill the issue template
