### ISSUE TITLE
Portrait or Landscape fixed 

### ISSUE THREAD

**Issue by xiaopn166** [dogo/SCLAlertView#201]
is it support fixed direction? or will be support? I have an APP that some ViewControllers fixed Portrait and some ViewControllers not . when I show the SCLAlertView in the Portrait ViewController ,then change the iPhone to Landscape ,the StatusBar follow it to change, it's not want. if you can add a property to fixed direction,it will be better!

**Comment by dogo** [comment]
Please fill the issue template
