### ISSUE TITLE
Table title overlay of SCLAlertView

### ISSUE THREAD

**Issue by ipaddr** [dogo/SCLAlertView#206]
When I have table view and I click one of it, it will shown the SCLAlertView. I able to scroll outside of SCLAlertView. Unfortunately, when I scroll back to the SCLAlertView, title of table section overlay the SCLAlertView as shown at screen shot below.

<img width="322" alt="screen shot 2016-05-18 at 3 36 05 pm" src="https://cloud.githubusercontent.com/assets/5902218/15354182/941e8c14-1d16-11e6-9456-b0b38f55370a.png">

**Comment by ciumexan** [comment]
same problem here...

**Comment by i-am-chris** [comment]
Hello please explain this in code: 

 [alert showSuccess:**self.parentViewController** title:@"Success!" subTitle:@"You accepted!" closeButtonTitle:nil duration:0.0f]; 

this is how you solve the scrolling issue on tableview
