### ISSUE TITLE
Custom button height

### ISSUE THREAD

**Issue by mrtv** [dogo/SCLAlertView#207]
Hi, 
I couldn't find any way to change the height of alert buttons. It would be really nice to have this option.

**Comment by dogo** [comment]
currently the only way is :

``` Objective-c
   // Init Alert

    // Add button
    SCLButton *button = [alertView addButton:LocalizedString(@"Button") actionBlock:^{
        completionBlock();
    }];

    // change frame size
    CGRect okButtonFrame = button.frame;
    okButtonFrame.size.height = DESIRED_HEIGHT;
    button.frame = okButtonFrame;
    
   // Show alert
```

**Comment by twostraws** [comment]
In case anyone else comes across this: this code doesn't actually work as you'd expect, because even though you can change the height of any button the alert view won't be resized to take that new size into account.
