### ISSUE TITLE
Statusbar Visible when showing the SCLAlertView

### ISSUE THREAD

**Issue by pangelovski** [dogo/SCLAlertView#208]
Hi, I have a ViewController where I am hiding the statusbar but when displaying the alertview the statusbar pops up during the show and then the statusbar hides after the alertview is dismissed.
How can I prevent the statusbar from showing?

**Comment by dogo** [comment]
```Objective-c
/** Set status bar hidden.
 *
 * Status bar hidden
 */
@property (nonatomic) BOOL statusBarHidden;

/** Set status bar style.
 *
 * Status bar style
 */
@property (nonatomic) UIStatusBarStyle statusBarStyle;
````
