### ISSUE TITLE
Tap inside the alert will dismiss the alert when using new window and shouldDissmissOnTapOutside=YES

### ISSUE THREAD

**Issue by jackyzh** [dogo/SCLAlertView#211]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- SCLAlertView version: `1.0.3`
- Device OS version: `9.0`
- Device Name: `iPhone 5s`
###### Reproduction Steps

Add an alert with new window and set `shouldDismissOnTapOutside` to `YES`.
###### Expected Result

Tap outside should disappear the alert but tap title or circle shouldn't disappear it.
###### Actual Result

Tap anywhere will disappear the alert include circle image, title label ...
### Tell us what could be improved:

Maybe you could add touchEvent rather than tapGesture when using new window. And figure out if the position of touch is inside/outside the alert view.

**Comment by mmahkamov** [comment]
Having the same issue with SCLAlertView version: 1.0.5.
The alert is dismissed if the user accidentally taps on it (e.g. misses a button).

**Comment by Connerli** [comment]
I have the same issue.

**Comment by dogo** [comment]
@jackyzh 
@mmahkamov 
@Connerli 
Please update to 1.1.2

**Comment by Connerli** [comment]
@dogo Resolved, thank you.
