### ISSUE TITLE
is it possible to change subtitle text while alert is showing?

### ISSUE THREAD

**Issue by invisible66** [dogo/SCLAlertView#213]
- [+] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.0.3`
 - Device OS version: `9.3.3`
 - Device Name: `iPhone 5S`
 
###### Reproduction Steps
 1. Replace subtitle dynamically

I want to show percentage while uploading data to server. how can i change the subtitle while waiting alert is showing?

**Comment by dogo** [comment]
Hi, you can set the subtitle text to nil and add a custom view to show the upload/download progress.

```
/** Add a custom UIView
 *
 * @param customView UIView object to be added above the first SCLButton.
 */
- (UIView *)addCustomView:(UIView *)customView;
```
