### ISSUE TITLE
Can't set selected on SCLSwitchView

### ISSUE THREAD

**Issue by TSCombine** [dogo/SCLAlertView#214]
Setting the switch to preselected doesn't seem to work    

SCLAlertView *alert = [[SCLAlertView alloc] init];
SCLSwitchView *switchView = [alert addSwitchViewWithLabel:@"Use local maps"];
[switchView setSelected:true];

Also tried
[[SCLSwitchView appearance]setSelected:true];

But without luck.

Is this not possible ? Thanks

**Comment by dogo** [comment]
Fixed by PR #226
