### ISSUE TITLE
 Conflict with the IQKeyboardManager

### ISSUE THREAD

**Issue by hongdong** [dogo/SCLAlertView#215]
Conflict with the IQKeyboardManager

**Comment by dogo** [comment]
What? Could you please describe the issue

**Comment by hongdong** [comment]
![2016-08-11 15_26_26](https://cloud.githubusercontent.com/assets/5499518/17581401/2606e9b0-5fd8-11e6-9855-62a68022fea1.gif)

see  ！！！when touchoutside

**Comment by glennposadas** [comment]
Hi, have you solved this? I'm filing a sweet issue later about managing keyboards too and animating the alert upwards using IQKeyboardManager.

**Comment by dogo** [comment]
Hi @hongdong  as the IQKeyboardManager warning disclaimer says :

If IQKeybaordManager conflicts with other third-party library, then it's developer responsibility to enable/disable IQKeyboardManager when presenting/dismissing third-party library UI. Third-party libraries are not responsible to handle IQKeyboardManager.

https://github.com/hackiftekhar/IQKeyboardManager

**Comment by glennposadas** [comment]
SOLVED: Disable the IQKeyboardManager before showing the alert, and enable the libabry when the user idmiss the alert.
