### ISSUE TITLE
Border color

### ISSUE THREAD

**Issue by pangelovski** [dogo/SCLAlertView#216]
Im presenting my alertView with the following parameters but for some reason the alertView has a grey border. Is it possible to hide the grey border?

   SCLAlertView *alert = [[SCLAlertView alloc] init];
    
    //Dismiss on tap outside (Default is NO)
    alert.shouldDismissOnTapOutside = YES;
    
    //Show animation type (Default is SlideInFromTop)
    alert.showAnimationType = SlideInFromBottom;
    
    //Hide animation type (Default is FadeOut)
    alert.hideAnimationType = SlideOutToBottom;
    
    //Set background type (Default is Shadow)
    alert.backgroundType = Transparent;
    
    //Overwrite SCLAlertView (Buttons, top circle and borders) colors
    alert.customViewColor = [KopigoUtility lightGray];
    
    //Set custom tint color for icon image.
    alert.iconTintColor = [KopigoUtility lightGray];
    
    //Override top circle tint color with background color
    alert.tintTopCircle = NO;
    
    //Set custom corner radius for SCLAlertView
    alert.cornerRadius = 10.0f;
    
    //Overwrite SCLAlertView background color
    //alert.backgroundViewColor = [UIColor cyanColor];
    
    //Returns if the alert is visible or not.
    //alert.isVisible;
    
    //Make the top circle icon larger
    alert.useLargerIcon = NO;
    
    //set button font
    [alert setButtonsTextFontFamily:kFontHelveticaNeueLight withSize:16];

**Comment by pangelovski** [comment]
Found out about the customViewColor property

**Comment by pangelovski** [comment]
Found out about the customViewColor property

**Comment by dogo** [comment]
@pangelovski currently it's not possible, sorry.
