### ISSUE TITLE
carthage update fail for special platform

### ISSUE THREAD

**Issue by tinpont** [dogo/SCLAlertView#217]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.0.3`
 - Device OS version: none
 - Device Name: none
 
###### Reproduction Steps
 1. Enter project root folder
 2. Execute command "carthage update --platform iOS"

###### Expected Result
Install normal.

###### Actual Result
Throwing error
> *** Skipped building SCLAlertView due to the error:
> Dependency "SCLAlertView" has no shared framework schemes for any of the platforms: iOS
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/dogo/SCLAlertView/issues/new

### Tell us what could be improved:
Support carthage for special platform.

**Comment by dogo** [comment]
@alokard Could you please, take a look on this?

**Comment by alokard** [comment]
Sure, will take a look this weekend.

**Comment by alokard** [comment]
Hey, @tinpont. Does your `Cartfile` looks like this:

```
github "dogo/SCLAlertView" "master"
```

You need to specify the master branch cause there was no new release with Cartage support yet.

There was a warning `no umbrella header found` but I've fixed it in attached PR

**Comment by alokard** [comment]
@dogo may I ask you to add new tag after closing this issue. Carthage, by default, checkouts the latest tag from git so it checkouts `1.0.3` version that doesn't have dynamic framework target for Carthage.

**Comment by dogo** [comment]
@alokard thanks for the heads up. I'm not a Carthage user hehehe.
version 1.0.5 is live

@tinpont please try again
