### ISSUE TITLE
Space, when no Title, SubTitle and Image.

### ISSUE THREAD

**Issue by NikKovV** [dogo/SCLAlertView#218]
I use custom View and got a space at the top, when there are no other elements. How to remove it?

![screen shot 2016-09-06 at 17 13 26](https://cloud.githubusercontent.com/assets/16647690/18276993/8d2167a6-7455-11e6-812c-f3ed52ae192b.png)

**Comment by dogo** [comment]
@NikKovV could you please test the develop branch?
Thanks

**Comment by NikKovV** [comment]
Works well

**Comment by dogo** [comment]
Please update to 1.0.5 @NikKovV
