### ISSUE TITLE
Command failed due to signal: Segmentation fault: 11 swift 3

### ISSUE THREAD

**Issue by billionbucks** [dogo/SCLAlertView#221]
i'm getting this buildtime error `Command failed due to signal: Segmentation fault: 11` after updating to Xcode3 how can fix it ? error's logs contains the `SCLAlertView` class's name well the logs are not helpful though for tracing out the cause of this error

**Comment by dogo** [comment]
swift? this project is the objective-c version

**Comment by KodiKraig** [comment]
Getting this same error. In my project everywhere I used SCLAlertView constructor or any calls to the framework, its broken after the conversion. Not sure how to solve this problem other than removing all the code using the SCLAlertView.
