### ISSUE TITLE
There is a Coverage Problem if do not write title and subtitle!

### ISSUE THREAD

**Issue by yusirxiaer** [dogo/SCLAlertView#222]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- SCLAlertView version: `1.0.5`
- Device OS version: `9.3`
- Device Name: `iPhone 7`
###### Reproduction Steps

 1.do not write title and subtitle 
 2.add button 
 3.there is a Coverage Problem
###### Expected Result

they don't cover.
###### Actual Result

![image](https://cloud.githubusercontent.com/assets/17606840/18671619/61f1e20e-7f77-11e6-9910-901c06263f07.png)

**Comment by dogo** [comment]
Ops! my bad, I will fix this. Sorry
