### ISSUE TITLE
Keyboard pushes up the SCAlertView with IQKeyboardManager

### ISSUE THREAD

**Issue by glennposadas** [dogo/SCLAlertView#223]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: The latest version via cocoapods
 - Device OS version: `9.3`
 - Device Name: `iPhone 5s simulator`
 
###### Reproduction Steps
 1. Use IQKeyboard Manager to your app
 2. Show the SCAlertView with textField
 3. Rotate the iPhone to Landscape
 4. Tap the textField to show the keyboard

###### Expected Result
IQKeyboard Manager should fully manage the keyboard nicely.
The keyboard should just cover up the buttons and should not push the alertview to top.
###### Actual Result
The keyboard pushes the Alert View to top with results to the textField not being hsown.
### Tell us what could be improved:

![screen shot 2016-10-04 at 7 46 31 pm](https://cloud.githubusercontent.com/assets/12502679/19073046/4ececefe-8a6b-11e6-9761-a61521e0aeba.png)

**Comment by dogo** [comment]
Hi @glennposadas as the IQKeyboardManager warning disclaimer says : 

 If IQKeybaordManager conflicts with other third-party library, then it's developer responsibility to enable/disable IQKeyboardManager when presenting/dismissing third-party library UI. **Third-party libraries are not responsible to handle IQKeyboardManager.**


https://github.com/hackiftekhar/IQKeyboardManager

**Comment by glennposadas** [comment]
SOLVED: Disable the IQKeyboardManager before showing the alert, and enable the libabry when the user idmiss the alert.
