### ISSUE TITLE
One of the two will be used. Which one is undefined.

### ISSUE THREAD

**Issue by JsonFu** [dogo/SCLAlertView#225]
When I run the emample it will print :
Class SCLSwitchView is implemented in both /Users/xxx/Library/Developer/Xcode/DerivedData/SCLAlertView-dojnvneelxdzkechfwggltvyjazr/Build/Products/Debug-iphonesimulator/SCLAlertViewFramework.framework/SCLAlertViewFramework (0x111d9bc80) and /Users/xxx/Library/Developer/CoreSimulator/Devices/19734992-DA5F-444D-B0BA-4683F94357CE/data/Containers/Bundle/Application/50045553-002C-4FAD-BA53-FDC5ADB55E66/SCLAlertView.app/SCLAlertView (0x10f80b7d0). One of the two will be used. Which one is undefined.
- SCLAlertView version: `1.0.5`
-  iOS simulator version: `10.0`
- simulator Name: `iPhone 7`
  how deal with  it ?

**Comment by dogo** [comment]
fixed
