### ISSUE TITLE
Not centered vertically when presented in navigation controller

### ISSUE THREAD

**Issue by DanielCardonaRojas** [dogo/SCLAlertView#231]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `~> 1.0`
 - Device OS version: `9.0`
 - Device Name: `iPhone 9`
 
###### Reproduction Steps
 1. Create a SCLAlertView from within a navigation controller
 2. Present
 3. Doesn't get centered vertically.

###### Actual Result
![pedir_turno](https://cloud.githubusercontent.com/assets/5472687/20627358/6d91e010-b2ed-11e6-9f9e-b72a27611fdb.png)

### Tell us what could be improved:

It would be nice to have some extra properties to change the alerts position. Maybe even have the overlay cover the navigation bar too.

**Comment by dogo** [comment]
https://github.com/dogo/SCLAlertView/issues/219
