### ISSUE TITLE
XCode 8.2 language error

### ISSUE THREAD

**Issue by colditz18** [dogo/SCLAlertView#235]
Just installed xcode 8.2 and my working code shows now the error

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

I've tried to set "Use Legacy Swift Language Version" to NO but still does not work

I'm using cocoa pods with pod 'SCLAlertView'

Thanks in advance

**Comment by dogo** [comment]
Hi @colditz18 , 

This is the Objetive-c version of SCLAlertView 

``
pod 'SCLAlertView-Objective-C'
```
