### ISSUE TITLE
window does not disappear when use hideView on first app run

### ISSUE THREAD

**Issue by AnaTeresaNeto** [dogo/SCLAlertView#237]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.1.0`
 - Device OS version: `10.2`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1. run app
 2. tap on alert to dismiss
 3. need to second tap on alert to really dismiss it, but only the first time the app run in a specific

###### Expected Result

alertview should dismiss.

###### Actual Result

need to tap a second time to dismiss the alertview

**Comment by dogo** [comment]
Everything is fine here, could you please provide more information
