### ISSUE TITLE
delegate 应该使用weak修饰，否则会造成循环引用  SCLAlertView.swift    Line 76

### ISSUE THREAD

**Issue by pengshengsongcode** [dogo/SCLAlertView#240]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.0.3`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1.
 2.
 3.

**Comment by dogo** [comment]
This is the object-c version, and I cant read Japanese :(

Open the issue here : https://github.com/vikmeup/SCLAlertView-Swift
