### ISSUE TITLE
Access a Button

### ISSUE THREAD

**Issue by mukulm24** [dogo/SCLAlertView#242]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.0.3`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1.Create a SCLAlertView
 2.Add a button to it
 

###### Expected Result
How do i change the properties of this button on its tap.

let changeButton = alert.addButton("Change Password") {
//button clicked
//change button color ( i cannot use change button as it is inside its own initializer.) any other way than adding target manually)
//button operations

}

**Comment by johnyluyte** [comment]
Don't know if this is the right way to do it. But I usually use the showCustomSubview example to create my own button: 

    func showCustomSubview() {
        alert = SCLAlertView(appearance: appearance)
        alert.showInfo("title")        
            
        // Customize your button
        let confirmButton = UIButton(frame: CGRect(x: 0, y: 0, width: 100, height: 100))    
        // Change event listener to "tap" if needed
        confirmButton.addTarget(self, action: #selector(self.onClickConfirmButton), for: .touchDown)

        let subview = UIView(frame: CGRect(x: 0, y: 0, width: 100, height: 100)
        subview.addSubview(confirmButton)
        alert.customSubview = subview
    }
    
    func onClickConfirmButton() {
        alert.hideView()
        // do something
    }
