### ISSUE TITLE
SCLAlertView should build without warnings

### ISSUE THREAD

**Issue by iosdev-republicofapps** [dogo/SCLAlertView#243]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.1.0`
 - Device OS version: `10.2.1`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1. Compile an app using SCLAlertView (through CocoaPods) in Xcode Version 8.2.1 (8C1002) on OS X 10.12.3.
 2. No other steps
 3.

###### Expected Result

SCLAlertView code should not generate warnings.

###### Actual Result

SCLAlertView does generate warnings:

/Users/joel/src/GetLive/Pods/SCLAlertView-Objective-C/SCLAlertView/SCLButton.h:104:11: Parameter 'windowWith' not found in the function declaration
Did you mean 'windowWidht'

**Solution: correct spelling of parameter in code doc to avoid warning.**

/Users/joel/src/GetLive/Pods/SCLAlertView-Objective-C/SCLAlertView/SCLButton.h:104:11: Parameter 'windowWith' not found in the function declaration
Did you mean 'windowWidht'

**Solution: correct spelling of parameter in code doc to avoid warning.**

### Tell us what could be improved:

We like to have clean builds without warnings, but cannot, because SCLAlertView code is creating warnings.  I don't want to go in and alter local SCLAlertView code since that would get overwritten with the next update of same through cocoapods.

I could create a PR to fix these if you'd be willing to review and issue a release?  :-)

**Comment by iosdev-republicofapps** [comment]
One more, sorry:


Warning: no rule to process file '/Users/joel/src/GetLive/Pods/SCLAlertView-Objective-C/SCLAlertView/comic-sans.ttf' of type file for architecture x86_64

**Comment by dogo** [comment]
Fixed, please update to 1.1.1.

Thanks @iosdev-republicofapps

**Comment by iosdev-republicofapps** [comment]
No, thank you!  :-)

**Comment by iosdev-republicofapps** [comment]
Thanks @dogo .  I upgraded to 1.1.1 and that fixed those warnings.  But now I get another warning (that was not there in the previous version of SCLAlertView):

```
file:///Users/joel/src/GetLive/Pods/SCLAlertView-Objective-C/SCLAlertView/comic-sans.ttf: warning: Missing file: /Users/joel/src/GetLive/Pods/SCLAlertView-Objective-C/SCLAlertView/comic-sans.ttf is missing from working copy
```

Did this font file get removed from the pod?

**Comment by iosdev-republicofapps** [comment]
Hmm, the font warning went away after I git committed the updated pod.  Sorry for the false alarm.
