### ISSUE TITLE
SCLAlertview in a new window. (No UIViewController) : The window cannot be closed

### ISSUE THREAD

**Issue by arkilis** [dogo/SCLAlertView#246]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.1.0`
 - Device OS version: `9.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1. Pad Install 
 2. Code:
`SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindowWidth:300.0f];
        [alert  showError:@"Error"
                subTitle:@"Some Text!"
                closeButtonTitle:@"OK" duration:0.0f]; // Error
`
 3. The alert window cannot be closed

###### Expected Result

Click `ok` to dismiss the window

###### Actual Result

Nothing happened

**Comment by dogo** [comment]
@arkilis , I tested your code and works fine, the window is dismissed. could you please provide more information ?

**Comment by arkilis** [comment]
`@implementation LoadDataAtFirstTimeRun

+(void)startApplication{
    
    // detect the Internet reachbility
    Reachability *hostReachability = [Reachability reachabilityWithHostName:REMOTEHOSTNAME];

    if([hostReachability currentReachabilityStatus] != NotReachable){
        
        // Serialization on species/parts
        [SpeciesRealmManager getAllSpecies:nil];
        
        // Serialization on growth stages
        [GrowthStageRealmManager getAllGrowthStages:nil];
        
    }else{
        // never run app under network before
        NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
        BOOL isSyned = [defaults stringForKey:SYNCFLAG];
        if(!isSyned){
            SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindowWidth:300.0f];
            [alert  showError:@"Error"
                     subTitle:@"The Internet is not reachable, make sure you lanuch the app under the Internet in the first time!"
             closeButtonTitle:@"OK" duration:0.0f]; // Error
        }
    }
}`

**Comment by dogo** [comment]
Humm the problem isn't the static function, probably is the life cycle. Where in the app or UIViewController life cycle the static method is called? Something like ViewDidLoad is wrong, should be ViewDidAppear or WillApper

**Comment by mikelrmb** [comment]
same issue @arkilis figure out?

**Comment by arkilis** [comment]
no, I found out,  this only can be called from viewcontroller class @mikelrmb
