### ISSUE TITLE
Problem in increasing height of TextField & customize the Alert view colour & image & button

### ISSUE THREAD

**Issue by vinayakpal** [dogo/SCLAlertView#253]
Please help with the above mention problem

**Comment by dogo** [comment]
Could you please post a sample ?

**Comment by vinayakpal** [comment]
i need to enter at maximum 150 characters in the text field but i won't shows the previous text we have enter as the text field height is default 30.f . is there any facility that height of textfield will automatically increase as long as we added text inside text field for clear view of all text.
I hope you gonna understand the problem by attached image. Thank you. Love to hear back from you ASAP

![mkcxl](https://user-images.githubusercontent.com/31687604/30596638-5c85f278-9d72-11e7-8cc2-107ded8037bc.jpg)

**Comment by vinayakpal** [comment]
Hi, i as posted earlier could you please give me a solution that how can i dynmically increase my textView Height as i dont want all the text in single line.

**Comment by dogo** [comment]
Please fill the issue template
