### ISSUE TITLE
i need to add on the preloaded text in the text field before textfield Alert pop up

### ISSUE THREAD

**Issue by vinayakpal** [dogo/SCLAlertView#254]
i've a concern regarding the textfield preloaded text as i need to edit the detail of user display name so whenever user want to edit the name he/she pop up the text field alert. So the text field in alert shows the previous name that mention in the app.

**Comment by dogo** [comment]
What? Could you please explain me what you want and what's the problem? I don't understand your issue (When you open issues, please fill the issue template)

**Comment by vinayakpal** [comment]
![img-0371](https://user-images.githubusercontent.com/31687604/30596110-d5fddaaa-9d70-11e7-9007-0464a1204ff3.PNG)
![img-0372](https://user-images.githubusercontent.com/31687604/30596111-d6006c52-9d70-11e7-9487-427c85bd08c0.PNG)

Above mention image will clear you what exactly i'm asking

I made an custom alert where user need to add their name during editing their profile.
Now, as image one shows the placeholder says"please enter your name" thats Fine!!!!
But what i need is when i call the Alert a preloaded display name to be already pleaced inside the text field. As this option is possible if we gonna work with default alert controller as (textField.text = @"vinayak"). So, exactly this option i want in this library. So can you help me out now.

**Comment by dogo** [comment]
Please fill the issue template
