### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by KelvinEC** [dogo/SCLAlertView#255]
I'm using Carthage to manage my dependencies. I can downlod, build and link framework, but when i try to import it into Objective-c code `#import <SCLAlertViewFramework/SCLAlertViewFramework.h>` i'm receiving `Cannot find interface declaration for 'SCAlertView', superclass of 'MyAlertView'`. How can i proceed?

###### Include the following:
 - SCLAlertView version: `1.1.2`
 - Device OS version: `9.0`
 - Device Name: `iPhone 6`

**Comment by anhhtbk** [comment]
I have same issue

**Comment by dogo** [comment]
Please update to 1.1.3
