### ISSUE TITLE
Use the builder pattern to build a SCLAlertView?

### ISSUE THREAD

**Issue by Sweeper777** [dogo/SCLAlertView#256]
The constructor of `SCLAlertView.SCLAppearance` is really long. When it is shown in Xcode's autocomplete thingy, I can't see what each parameter's name is and I can't select only the few parameters that I need either.

I suggest that there  should be a builder class for `SCLAlertView`, so this code:

    SCLAlertView(appearance: SCLAlertView.SCLAppearance(showCloseButton: false))

can just be

    SCLAlertViewBuilder()
        .showCloseButton(false)
        .build()

This way, when you type `.` Xcode will tell you what options there are and it is easy to scroll through them or start typing and let Xcode guess which one you want.

Is this a good idea?

**Comment by dogo** [comment]
@Sweeper777 Please read the **Fluent style** section
