### ISSUE TITLE
 not supporting for Swift 4.0

### ISSUE THREAD

**Issue by msplapps** [dogo/SCLAlertView#257]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.0.3`
 - Device OS version: `6.0`
 - Device Name: `iPhone 6`
 
###### Reproduction Steps
 1.
 2.
 3.

**Comment by dogo** [comment]
Closing, Issues must be have the issue template filled
