### ISSUE TITLE
Title truncated

### ISSUE THREAD

**Issue by BrunoMiguens** [dogo/SCLAlertView#259]
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - SCLAlertView version: `1.1.2`
 - Device OS version: `All`
 - Device Name: `All`
 
###### Reproduction Steps
 1. Add a medium/large title and you'll see the title truncated.

###### Expected Result

I think the title should have the ability of, at least, support 2 lines of text and grow the alert view with it.

**Comment by tester87** [comment]
Can make it title wrap or 2 lines of tittle? Please help

**Comment by dogo** [comment]
@BrunoMiguens @tester87 , please test the develop branch. 

Add support to two lines title #259 d3d90a5e7610af2e809b4db6855a1a858c8651e8
