### ISSUE TITLE
does not work with UIPIckview

### ISSUE THREAD

**Issue by atcnf3000** [dogo/SCLAlertView#26]
Thank you for the nice Alert Controller.

When I try to show the alert  under  PickerView delegate, like the following:

-(void)pickerView:(UIPickerView *)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component{

// if something  true I will give a warning to the user 
[alert showWarning....];
}
The UIAlertView works under such condition but not SCLAlertView, it displays on the very top of my tableview(should be on top of the pickerView like UIAlertView ), so I see very strange things like the alertView is transparent to the parent view and the PickerView background visible  far below ( pickerView is  located at the bottom of a long list static tableview  cells)

**Comment by dogo** [comment]
Try ti use 

self.parentViewController
