### ISSUE TITLE
SCLAlertViewHideAnimation wrong animations

### ISSUE THREAD

**Issue by EricoGT** [dogo/SCLAlertView#262]
Hey Diogo!

After updating to iOS 11.2.X, every time I use animation options to **hide** the alert (SCLAlertViewHideAnimation*), which has a variation of the alert position, a wrong animation is being generated. The alert is animated from the origin position to the current position and **not** from the current to off-screen position...

**Comment by dogo** [comment]
HI @EricoGT , could you please provide me a sample ?

**Comment by EricoGT** [comment]
https://youtu.be/0lLv577vfco

Please watch the video. In the first part I'll show you the problem. In a second example I go to the home menu and only after returning the application I tap the button to close the alert. It is the same alert with the same SCLAlertViewHideAnimation setting.

**Comment by dogo** [comment]
hum thanks for reporting. 
I'm investigating the issue and I realized that only happens with iOS 11+ and using ```SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];``` using the regular ```init```. seems fine.

**Comment by EricoGT** [comment]
In my tests, use regular `init` instead of `initWithNewWindow` result in the same effect.

**Comment by dogo** [comment]
@EricoGT Please update to 1.1.3
