### ISSUE TITLE
How to add in multiple subtitle in an alert view?

### ISSUE THREAD

**Issue by tester87** [dogo/SCLAlertView#266]
hi all,

How can I add in multiple subtiltle in an alert?
Please help. thank you

**Comment by Liqiankun** [comment]
Do you see this?
```
[alert showSuccess:self title:@"Hello World" subTitle:@"This is a more descriptive text." closeButtonTitle:@"Done" duration:0.0f];
```

**Comment by tester87** [comment]
Hi LiquanKun, Yes, I saw this but how can I add in multiple subtitle? Such as 
[alert showSuccess:self title:@"Hello World" subTitle:@"111"  subTitle2:@"222." closeButtonTitle:@"Done" duration:0.0f];

**Comment by dogo** [comment]
Hi @tester87 , it's not possible add multiple subtitles, but you can add a subtitle with break lines

**Comment by Liqiankun** [comment]
@dogo Good idea!
