### ISSUE TITLE
How to solve the problem of overlapping multiple calls in a controller?（如何解决在一个控制器中，连续多次调用，会出现重叠的情况？）

### ISSUE THREAD

**Issue by Michaelyb520** [dogo/SCLAlertView#267]
## 发现一个Bug，就是，如果在一个控制器中，使用initNewWindow，有时候，出现连续调用多次，会出现重叠的情况。怎么解决呢？多次重叠，屏幕直接黑屏了。。。。。

![image](https://user-images.githubusercontent.com/9857312/41337844-f0d5bf1c-6f22-11e8-8e9a-8d12fcd18ac1.png)

## 正常情况，应该是下面样式。。。

![image](https://user-images.githubusercontent.com/9857312/41337882-236fae4c-6f23-11e8-9d43-64330c49bde9.png)

**Comment by dogo** [comment]
@Michaelyb520 I don't know chinese, please report in english

**Comment by dogo** [comment]
dupe
