### ISSUE TITLE
How to solve the problem of overlapping multiple calls in a controller?（如何解决在一个控制器中，连续多次调用，会出现重叠的情况？）

### ISSUE THREAD

**Issue by Michaelyb520** [dogo/SCLAlertView#268]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

### Include the following:
 - SCLAlertView version: `1.1.3`
 - Device OS version: `11.0`
 - Device Name: `iPhone X`
 
### Reproduction Steps

One Bug found is that if you use initNewWindow in a controller, sometimes alert overlaps if you call the show method multiple times in a row. How? Multiple alert overlaps and the screen goes black...

发现一个Bug，就是，如果在一个控制器中，使用initNewWindow，有时候，如果连续调用多次show方法，alert会出现重叠的情况。怎么解决呢？多次alert重叠，屏幕直接黑屏了。。。。。

### Expected Result
![image](https://user-images.githubusercontent.com/9857312/41338312-64921094-6f24-11e8-9aec-bfe662ecbba4.png)

### Actual Result
Normally, it should be the following style...

正常情况，应该是下面样式。。。

![image](https://user-images.githubusercontent.com/9857312/41338336-785f4fe2-6f24-11e8-8a7a-66a39ac2c252.png)

### Tell us what could be improved:

When I expect to use initNewWindow, I can always guarantee that only one window will be displayed...

期望使用initNewWindow的时候，能始终保证只有一个window展示。。。。

**Comment by Michaelyb520** [comment]
## 解决办法：
### 1. 显示位置
![image](https://user-images.githubusercontent.com/9857312/41345461-48a1340c-6f36-11e8-8b5e-6e721c47cc5b.png)

### 2. 设置window位置
![image](https://user-images.githubusercontent.com/9857312/41345512-7d72f666-6f36-11e8-936f-929612c642c7.png)

### 3. 初始化位置
![image](https://user-images.githubusercontent.com/9857312/41345535-8fb152f0-6f36-11e8-86d7-7733646ac6c1.png)

### 4. 将SCAlertView类设置成单例，或者创建一个子类继承自SCAlertView类，并设置子类为单例

![image](https://user-images.githubusercontent.com/9857312/41345632-d37194c8-6f36-11e8-8da7-93eccb67ad4c.png)

**Comment by Michaelyb520** [comment]
### PS：上面问题基本上及解决了，又发现多次show的时候，结果是多次创建多个确认按钮，由此可见，这个库的Bug真的不少啊，请求大大们，尽快解决这个问题啊。。。。。

![image](https://user-images.githubusercontent.com/9857312/41349224-ca83e89c-6f41-11e8-8266-962ee91560f3.png)

**Comment by dogo** [comment]
@Michaelyb520 I don't know chinese, please report in english

**Comment by Michaelyb520** [comment]
@dogo I have roughly translated the above questions into English. Since I don't often use English, my English level is not very good and my translation ability is limited.
@dogo 已经将上述问题大致翻译成英文，由于不常使用英文，我的英文水平也不是很好，翻译能力有限，还望海涵。。。。
