### ISSUE TITLE
UIStatusBarStyle always appears as 'UIStatusBarStyleDefault'

### ISSUE THREAD

**Issue by EricoGT** [dogo/SCLAlertView#274]
Hello!
I have a project using the 'SCLAlertView' (Object-C) pod and even changing the statusBarStyle property to UIStatusBarStyleLightContent when the alert appears on the screen the statusBar shows as UIStatusBarStyleDefault.
This project uses "View controller-based status bar appearance = YES" and is in iOS version 11.4.
What could be happening?

**Comment by dogo** [comment]
Hi @EricoGT ,

You should set the statusBarStyle
/** Set status bar style.
 *
 * Status bar style
 */
@property (nonatomic) UIStatusBarStyle statusBarStyle;

Another question, which init method are you using? default `init` or `newWindow`?

**Comment by EricoGT** [comment]
I use:
```
SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];
alert.statusBarStyle = UIStatusBarStyleLightContent;
```
But it appears `UIStatusBarStyleDefault`.

**Comment by dogo** [comment]
It's broken since 1.1.3 =(. I'll try to fix it

**Comment by EricoGT** [comment]
I thank you for the effort.

**Comment by EricoGT** [comment]
Please take a look when you can:
[https://drive.google.com/open?id=1FISbGbdOh8wh3g3AiHeHPGrDTUGkb2Ym](url)

**Comment by EricoGT** [comment]
"Ainda há esperança de solução?"

**Comment by dogo** [comment]
Estou viajando a trabalho, não sei quando terei tempo de ver isso, mas sua solução acima não corrige o problema. Desculpa

**Comment by dogo** [comment]
Please fill the issue template

**Comment by dogo** [comment]
Proper issue #280
