### ISSUE TITLE
EXC_BAD_ACCESS (code=1)

### ISSUE THREAD

**Issue by lewishalliday** [dogo/SCLAlertView#28]
I'm having an issue with this.

I'm a big fan of SCLAlertView but i'm having an issue with a section within my code.

I am using the code elsewhere in my project but when using it within another view controller I'm receiving the above error.

It is showing itself within UIImage+ImageEffects.m on line [keyWindow.layer renderInContext:context]; within 
- (UIImage *)convertViewToImage

This is the code I am using to call the alert

SCLAlertView *alert = [[SCLAlertView alloc] init];
    UITextField *textField = [alert addTextField:@"Quantity"];
    [textField setKeyboardType:UIKeyboardTypeNumberPad];
    alert.backgroundType = Blur;
    alert.shouldDismissOnTapOutside = YES;
    [alert showSuccess:self title:@"Quantity" subTitle:@"Enter Quantity" closeButtonTitle:@"Done" duration:0.0f];

Thanks in advance

Edit: If i leave the alert view standard it works perfectly. It only seems to have an issue when customising the alert where it crashes

SCLAlertView *alert = [[SCLAlertView alloc] init];
    UITextField *textField = [alert addTextField:@"Quantity"];
    [textField setKeyboardType:UIKeyboardTypeNumberPad];
    alert.backgroundType = Blur;
    [alert showSuccess:self title:@"Quantity" subTitle:@"Enter Quantity" closeButtonTitle:@"Done" duration:0.0f];

That works fine

**Comment by mbcoder17** [comment]
I am having this same issue displaying it in a UITableViewController subclass.

**Comment by mbcoder17** [comment]
It crashes on this line: [keyWindow.layer renderInContext:context];

And this seems to be due to the fact that renderInContext cannot be called on a background thread: http://stackoverflow.com/questions/15135208/objective-c-renderincontext-crash-on-background-thread
