### ISSUE TITLE
UIStatusBarStyle always appears as 'UIStatusBarStyleDefault'

### ISSUE THREAD

**Issue by alexandrefurquim** [dogo/SCLAlertView#280]
**Describe the bug**
The property 'statusBarStyle' of SCLAlertView always show as 'UIStatusBarStyleDefault'.

**To Reproduce**

- Simply initialize the component as below:
```
SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];
alert.statusBarStyle = UIStatusBarStyleLightContent;
```

**Expected behavior**
The component should follow the style of the application as configured by the related property.

**Screenshots**
![img_1318](https://user-images.githubusercontent.com/36628384/46969583-f63d2000-d08c-11e8-9bf4-98ea2d18e90b.png)
![img_1319](https://user-images.githubusercontent.com/36628384/46969584-f63d2000-d08c-11e8-9682-8bc0d989cf7d.png)

**Smartphone (please complete the following information):**
- Device: All (iPhones and iPads)
- OS: iOS 9 (and higher, not tested in previus versions)
- Version: SCLAlertView 1.1.3 (and higher)

**Additional context**
The problem has already been verified and confirmed previously (June/2018).
No abnormal features of the applications that make use of this component have been found to help unravel the problem, unfortunately.

**Comment by dogo** [comment]
Proper issue #280
