### ISSUE TITLE
SCLAertView cannot be used in Shared Extension

### ISSUE THREAD

**Issue by tsvidya** [dogo/SCLAlertView#283]
Tried compiling SCLAlertView in the shared extension. But I get the following compiler error. 
'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

Is there an way out for this ?

**Comment by balusreekanth** [comment]
You can Set Require Only App-Extension-Safe API to “NO”. in build settings for  SCLAlertView target and compile . pic :  https://askadmin.com/sharedapplication-is-unavailable-not-available-on-ios-app-extension/
