### ISSUE TITLE
Nothing happens on show methods @ iOS 13 

### ISSUE THREAD

**Issue by bar2** [dogo/SCLAlertView#287]
**Describe the bug**
SCLAlertView instance not appearing when any of the show methods called (showSuccess, showError etc.)

**To Reproduce**
1. Build an app under XCode 11
2. Add SCLAlertView with Cocoapods
3. Initialize and call a show method from a SCLAlertView instance from viewDidAppear

**Expected behavior**
SCLAlertView instance to appear.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus Simulator
 - OS: 13.1
 - Version 

**Additional context**
I also tried this, on the same device (iPhone 8 Plus Simulator - 13.1), from an app built with the older SDK, and SCLAlertView is being shown.

**Comment by bar2** [comment]
If there is any additional data I can provide, I'd be happy to.

**Comment by dogo** [comment]
Seems okay here.

https://www.dropbox.com/s/sjr7jbxf5bswkz1/Screen%20Recording%202019-11-13%20at%2000.31.00.mov?dl=0
