### ISSUE TITLE
设置富文本后不居中显示了 变成了居左。

### ISSUE THREAD

**Issue by yangdehui** [dogo/SCLAlertView#288]
alert.attributedFormatBlock = ^NSAttributedString* (NSString *value)
    {
        NSMutableAttributedString *subTitle = [[NSMutableAttributedString alloc]initWithString:value];
        NSRange redRange = [value rangeOfString:currentModel.name options:NSCaseInsensitiveSearch];
        [subTitle addAttribute:NSForegroundColorAttributeName value:[UIColor redColor] range:redRange];
        return subTitle;
    };
测试发现代码中 textview.attributedText赋值后需重新设置一下textview.textAlignment属性，而您只在初始化做了设置。

**Comment by dogo** [comment]
English, please and describe your issue
