### ISSUE TITLE
Bug with Keyboard on iPad in Landscape

### ISSUE THREAD

**Issue by pnome** [dogo/SCLAlertView#297]
**Describe the bug**
With an iPad in landscape, and a dialog with a text field, when tapping in the text field, the keyboard covers the buttons of the dialog.

**To Reproduce**
1. Run the SCLAlertView-ObjectiveC example project on an iPad in landscape
2. Tap the "Show Edit" option
3. Tap in the text field
4. You can see it happening here: https://www.loom.com/share/7bc2516ff71240faac702304714811f6

**Expected behavior**
I expect the dialog to move up out of the way of the keyboard

**Smartphone (please complete the following information):**

**Additional context**
Notably, the same bug does not happen using the Swift SCLAlertView example code.
Also, if you tap Show Edit, then change to another app, then return, and THEN tap in the text field, everything works fine. This is a very strange bug.

**Comment by pnome** [comment]
Anybody have any ideas about this? It seems to work ok in the Swift version.

**Comment by hms040717007** [comment]
me too

**Comment by hms040717007** [comment]
Hope the author can solve it soon.thanks

**Comment by pnome** [comment]
I'd love to know if anybody has any ideas about this. Seems like a tricky one to fix.
