### ISSUE TITLE
Cannot find ChangesLog for version 1.2.0

### ISSUE THREAD

**Issue by giria** [dogo/SCLAlertView#299]
I cannot find the changeLog for version 1.2.0.

On the ChangeLog file, last entry is 1.1.4.

Where I can find a list of changes for 1.2.0 (SCLAlertView-Objective-C)?

Thanks

**Comment by dogo** [comment]
https://github.com/dogo/SCLAlertView/releases/tag/1.2.0

**Comment by giria** [comment]
Oh, I see. Thanks a lot.
