### ISSUE TITLE
Alert Positioning in TableView

### ISSUE THREAD

**Issue by DonBaronFactory** [dogo/SCLAlertView#32]
When triggering the Alert (which is btw absolutely great) in a TableView, when the tableview is scrolled to the very bottom, the positioning of the alert gets sometimes even out of screen and a weird background effect occurs (see screenshot)... Resigning the first responder and putting the focus back to a textfield which is at the beginning of the tableview doesn't help...

![ios simulator screen shot 06 dec 2014 13 02 21](https://cloud.githubusercontent.com/assets/10096944/5327308/a82a3a82-7d49-11e4-80e3-f99f99074c86.png)
![ios simulator screen shot 06 dec 2014 13 02 56](https://cloud.githubusercontent.com/assets/10096944/5327309/a83127c0-7d49-11e4-8b81-465a0420258a.png)

**Comment by ciumexan** [comment]
where did you put this piece of code? Thanks...

**Comment by ciumexan** [comment]
hello cre8it any news

**Comment by i-am-chris** [comment]
Hello please explain this in code.
