### ISSUE TITLE
Rotating with keyboard

### ISSUE THREAD

**Issue by DemianSteelstone** [dogo/SCLAlertView#36]
Hi! Nice alert view. But I have an issue on rotating with showed keyboard. Seems, coords calculation is not correct. I use it on iPhone.

**Comment by dogo** [comment]
iOS version ? could you please attach a screenshot please

**Comment by DemianSteelstone** [comment]
IPad mini 64 bit. IOS 7
![screen shot 2015-01-19 at 9 00 53](https://cloud.githubusercontent.com/assets/5743752/5796508/3a78c7d6-9fba-11e4-9433-c4ead4c01184.png)

Sorry, I don't remember, why I wrote, that it was on IPhone  :)

**Comment by dogo** [comment]
Please update to 0.4.0 and test again.

```pod update```

**Comment by DemianSteelstone** [comment]
![ios simulator screen shot 29 2015 10 10 52](https://cloud.githubusercontent.com/assets/5743752/5953773/5479573a-a79f-11e4-8ad7-6d02c59f2b55.png)

ios 7 ipad 2 simulator

**Comment by DemianSteelstone** [comment]
ios 7 ipad 2 simulator
Nothing changed
![ios simulator screen shot 29 2015 10 23 57](https://cloud.githubusercontent.com/assets/5743752/5953901/05b60c36-a7a1-11e4-851a-4b617c4ef673.png)


cocoapod SCLAlertView-Objective-C (0.5.2)

**Comment by dogo** [comment]
Seems fine here :
https://dl.dropboxusercontent.com/u/12595498/ipad-rotate.mov

Give me more info :D

**Comment by DemianSteelstone** [comment]
Hmmm..
Try to use it from splitViewController. From Detail or master.
Example:
https://www.dropbox.com/s/m0j6kvcwizvuwkc/SCLAllertTest.zip?dl=0
It's rotation seems good here, but background not covering entire screen.

**Comment by dogo** [comment]
To cover all background you need to use : 
```[[[UIApplication sharedApplication] keyWindow] rootViewController]```

as UIViewController
