### ISSUE TITLE
Long texts truncated

### ISSUE THREAD

**Issue by ddaddy** [dogo/SCLAlertView#38]
If I show an alert with some long text, the end is truncated.
Is it possible to either shrink the text size more when needed or preferably expand the height of the alert view to fit the text?

Thanks for this awesome work.

**Comment by dogo** [comment]
Added to TODO

**Comment by dogo** [comment]
Implemented :dancer: 

@frantzmiccoli @dagobert-duck @ddaddy , please update to 0.5.2

**Comment by frantzmiccoli** [comment]
Thanks !
