### ISSUE TITLE
alertview position issue

### ISSUE THREAD

**Issue by sergiollegaspi** [dogo/SCLAlertView#39]
I tried using this on one of my apps. It works well in UIViewController but got some issue in location when implementing in UITableViewController. What I did was I modified SCLAlertView.m and set the _backgroundView.frame to CGRectMake(0[x],0[y],vcWidth[width], vcHeight[as height]);. This is just a workaround not sure if you got a better solution. Thanks by the way for this awesome class:)

**Comment by dogo** [comment]
great
