### ISSUE TITLE
Is possible to bind action on default button?

### ISSUE THREAD

**Issue by cactis** [dogo/SCLAlertView#4]
thanks.

**Comment by zakhoy** [comment]
Hey there how can add simple  login username and password 





SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];

 [alert addTextField:@"username"];

[alert addTextField:@"Password"];



    [alert addButton:@"Show Name" actionBlock:^(void) {


   


 

timer(2) {
        setupMenu();
      });
    }];

**Comment by zakhoy** [comment]
User can be Able to login using username and password simple for example username is zaxo password is 123456
