### ISSUE TITLE
Tickbox enhancement

### ISSUE THREAD

**Issue by rando128** [dogo/SCLAlertView#40]
It would be useful to have to ability to add a tickbox to the alertview allowing the user to select "don't show  this again". Ideally with blocks:

//Using Blocks With Validation
[alert addTickbox:@"Don't show again" validationBlock:^BOOL {
    BOOL tickboxValue = ....
    return tickboxValue;

} actionBlock:^{
    // handle successful validation here
}];

**Comment by gmogames** [comment]
+1

**Comment by MarshalGeazipp** [comment]
+1

**Comment by dogo** [comment]
Please test the develop branch

```Objective-C
    SCLAlertView *alert = [[SCLAlertView alloc] init];
    
    SCLSwitchView *switchView = [alert addSwitchViewWithLabel:@"Don't show again".uppercaseString];
    switchView.tintColor = [UIColor brownColor];
    
    [alert addButton:@"Done" actionBlock:^(void) {
        NSLog(@"Show again? %@", switchView.isSelected ? @"-No": @"-Yes");
    }];
    
    [alert showCustom:self image:[UIImage imageNamed:@"switch"] color:[UIColor brownColor] title:kInfoTitle subTitle:kSubtitle closeButtonTitle:nil duration:0.0f];
```

**Comment by rando128** [comment]
Works great. Thx. From a UXD standpoint though, it might be better to place the switchView below the buttons.
