### ISSUE TITLE
iPad landscape orientation for iOS < 8 is not supported

### ISSUE THREAD

**Issue by anclefeudor** [dogo/SCLAlertView#41]
Need to add rotation for landscape ipad iOS < 8 ;(
![ios simulator screen shot 06 jan 2015 03 03 03](https://cloud.githubusercontent.com/assets/2716717/5622724/91c22c2c-9550-11e4-8663-d3a4fc280f70.png)

**Comment by RauruF** [comment]
I've have de same problem using SCLAlertView in iOS 7.

**Comment by dogo** [comment]
yep, bug! huahaua ! Add to TODO

**Comment by TheSpring** [comment]
it's not only iPad , it's also for iPhone/iPod running iOS<8
guess because of new iOS 8 API for orientation which are called different
![1](https://cloud.githubusercontent.com/assets/1254421/5739502/e2664100-9c02-11e4-98c0-b91d481dfd0f.png)

**Comment by dogo** [comment]
Fixed, please update to 0.3.9

**Comment by TheSpring** [comment]
Thanks ! works great !

**Comment by santoshsurve22** [comment]
dogo..Thanks. You are awesome
