### ISSUE TITLE
Change Edit Alert Color

### ISSUE THREAD

**Issue by Kfeavel** [dogo/SCLAlertView#43]
I don't believe that it is possible to change the color of the alert when it contains a UITextField. Maybe it could be changed to a format like that of adding another button, that way a custom alert could be set up and then a UITextField added.

**Comment by dogo** [comment]
```
    SCLAlertView *alert = [[SCLAlertView alloc] init];
    
    [alert addTextField:@"Enter your name"];

    UIColor *color = [UIColor colorWithRed:65.0/255.0 green:64.0/255.0 blue:144.0/255.0 alpha:1.0];
    [alert showCustom:self image:[UIImage imageNamed:@"git"] color:color title:@"Custom" subTitle:@"Add a custom icon and color for your own type of alert!" closeButtonTitle:@"OK" duration:0.0f];
```

**Comment by Kfeavel** [comment]
Is that format available in the latest version? Here is how I currently have mine coded:

SCLAlertView *alert = [[SCLAlertView alloc] init];
    UITextField *textField = [alert addTextField:@"i.e. Pick Up Milk"];
    [alert addButton:@"Done" actionBlock:^(void) {
       //block stuff
    }];
    
    [alert showEdit:self
              title:@"Title"
           subTitle:@"Subtitle"
   closeButtonTitle:@"Close"
           duration:0.0f];

**Comment by dogo** [comment]
yes, showCustom is available since 0.2.0. If you use showEdit will be always purple, you need to use showCustom

**Comment by Kfeavel** [comment]
I'll look into that and let you know if it works!

**Comment by Kfeavel** [comment]
This was indeed an issue on my part. I'm closing the issue. Thanks for your help!
