### ISSUE TITLE
Alert Moves After Keyboard Dismisses

### ISSUE THREAD

**Issue by Kfeavel** [dogo/SCLAlertView#44]
If an alert with a UITextField triggers another alert (any type), it will move from the center of the view to the bottom when the keyboard disappears. I've provided an example below:

    SCLAlertView *alert = [[SCLAlertView alloc] init];
    UITextField *textField = [alert addTextField:@"Text Field"];
    
    [alert addButton:@"Done" actionBlock:^(void) {
    // Executed when "Done" is pressed.
        if ([*condition goes here*]) {
            SCLAlertView *alert2 = [[SCLAlertView alloc] init];
            alert2.shouldDismissOnTapOutside = YES;
            [alert2 showCustom:self
                         image:[UIImage imageNamed:@"Image Name"]
                        color:[UIColor flatMagentaColor]
                        title:@"Title 2"
                     subTitle:@"Subtitle 2"
             closeButtonTitle:@"Close 2"
                     duration:0.0f];
            // At this point the keyboard would disappear and the alert would slide down to the bottom of the view with it.
        } else {
    // Go about your normal business and no bugs appear
        }
    }];
    
    [alert showEdit:self
              title:@"Title"
           subTitle:@"Subtitle"
       closeButtonTitle:@"Close"
               duration:0.0f];

**Comment by dogo** [comment]
humm, seems fine here

https://dl.dropboxusercontent.com/u/12595498/Untitled.mov

**Comment by Kfeavel** [comment]
Huh. It certainly isn't behaving that way for me. I'm running on an iPhone 5 (iOS 8.2 Beta) if that helps at all.

**Comment by dogo** [comment]
Humm, okay more info is always good :P. I will test later with the beta

**Comment by portwatcher** [comment]
I have the same issue. 

It seems the alert shows before the previous showing keyboard complete hiding animation. So the `UIKeyboadDidHideNotification` triggers after alert shows, alert will move a bit down in order to adjust itself position.

I think we the developers should take this situation into consideration. The SCLAlertView does nothing wrong.

We should present alert **after** the previous keyboard hides.

**Comment by Kfeavel** [comment]
@portwatcher I'll see if there is something I can do to fix that. It might be worth noting that `UIKeyboardDidHideNotification` may not be the best way to go about moving the alert view. I recently opened another issue that might also be caused by `UIKeyboardDidHideNotification`.

**Comment by dogo** [comment]
Fixed. Update to 0.4.0
