### ISSUE TITLE
iPad vs iPhone NavigationBar

### ISSUE THREAD

**Issue by TripleJB** [dogo/SCLAlertView#46]
Hello, 
SCLAlertView is great. I want to implement it in an update for my Swift learning app Swifty.

I noticed that there is a different behavior when showing the alert.
See the attached screenshot for more information!

![bug](https://cloud.githubusercontent.com/assets/5963790/5774641/4c016d88-9d70-11e4-995d-3257cf08565d.png)

**Comment by ddaddy** [comment]
I've also seen this on an iPhone when the View Controller is embeded in a Nav Controller.
Only since the latest update.
Addong it back to UIWindow fixes it.

**Comment by dogo** [comment]
Try to use on iPad

```
[[[UIApplication sharedApplication] keyWindow] rootViewController];
```

**Comment by TripleJB** [comment]
Thanks for the quick reply!
This is how I use it in my ViewController, that is embedded in an NavigationController:

<code>SCLAlertView *alert = [[SCLAlertView alloc] init];</code>
<code>[alert showCustom: ...];

What do you mean by using the rootViewController?

**Comment by dogo** [comment]
```
   SCLAlertView *alert = [[SCLAlertView alloc] init];

UIViewController *rootViewController = [[[UIApplication sharedApplication] keyWindow] rootViewController];    

    UIColor *color = [UIColor colorWithRed:65.0/255.0 green:64.0/255.0 blue:144.0/255.0 alpha:1.0];
    [alert showCustom: rootViewController image:[UIImage imageNamed:@"MY_IMAGE"] color:color title:@"Custom" subTitle:@"Add a custom icon and color for your own type of alert!" closeButtonTitle:@"OK" duration:0.0f];
```

**Comment by dogo** [comment]
Another try is use ```self.navigationController``` as first param

**Comment by TripleJB** [comment]
Thank you very much. Still not everything is dark. This looks odd.
![img_0099](https://cloud.githubusercontent.com/assets/5963790/5788772/ea7a60ee-9e49-11e4-9287-82c5521dccfc.PNG)

**Comment by TripleJB** [comment]
Another bug: If I change ViewController after showing the alert, my NavigationBar disappears.

**Comment by dogo** [comment]
http://stackoverflow.com/questions/19857152/battery-icon-jump-to-front-my-overlay-when-battery-loading-or-low

Its a default behaviour
