### ISSUE TITLE
Landscape not working on iPad

### ISSUE THREAD

**Issue by Zarkwizard** [dogo/SCLAlertView#48]
I was running some tests with the components, and I noticed it doesn't seem to rotate on an iPad using 

7.0.4
IPad 3

When it runs in the simulator it works fine, but on the actual device it fails.   The tests were performed using the test app.  I have included an image from the iPad.
![img_0021](https://cloud.githubusercontent.com/assets/1426208/5795446/089bf6f2-9f56-11e4-8f06-92945b324ac5.PNG)

I also noticed if I run it in Landscape on my iPhone 5 with the same OS version it too displays the alert in portrait, even while the device is landscape.

Any suggestions?

Awesome work.

**Comment by dogo** [comment]
Hi, which version you are using?

**Comment by Zarkwizard** [comment]
I went and looked and I saw there was an update from 2 days ago, the code I was using was probably about 6 days ago.  It appears that the issue was actually fixed recently.  The latest code works flawlessly.

Thanks for checking in.  It's a really nice alert.

**Comment by dogo** [comment]
Great! :D
