### ISSUE TITLE
Can i write the code anywhere?

### ISSUE THREAD

**Issue by heyehao2008** [dogo/SCLAlertView#49]
Can i write the code anywhere,not limit to viewController?
i just find the method to add alert view must have a parameter that is viewController's object.

**Comment by dogo** [comment]
You always will need a viewController, but you can use the root or the parent


```UIViewController *viewController = [[[UIApplication sharedApplication] keyWindow] rootViewController]; ```

or

```UIViewController *viewController = self.navigationController;```

```
SCLAlertView *alert = [[SCLAlertView alloc] init];
[alert showSuccess: viewController title:@"Hello World" subTitle:@"This is a more descriptive text." closeButtonTitle:@"Done" duration:0.0f];```

**Comment by heyehao2008** [comment]
oh,yaeh! thanks a lot!
