### ISSUE TITLE
Display in formsheet

### ISSUE THREAD

**Issue by tlextrait** [dogo/SCLAlertView#50]
The alert will display off-centered if showed from a modal presented in form sheet style on the iPad.

**Comment by dogo** [comment]
![ios simulator screen shot jan 19 2015 3 22 51 pm](https://cloud.githubusercontent.com/assets/1487375/5804659/0f68f0e0-9fef-11e4-916e-760e137c6c3c.png)

like this?

**Comment by dogo** [comment]
and you want to achieve? :

![ios simulator screen shot jan 19 2015 3 29 31 pm](https://cloud.githubusercontent.com/assets/1487375/5804780/0586f80a-9ff0-11e4-81fe-5872fb68bb7d.png)

**Comment by tlextrait** [comment]
Yup!

**Comment by dogo** [comment]
hehehe, nope! It's a bug 0o 
Could you please test the upstream code?

**Comment by tlextrait** [comment]
Damn I was hoping it was my fault. I'll test

**Comment by tlextrait** [comment]
Actually I just realized it's swift so I can't test, never used swift, I wouldn't know how to test it (in a timely fashion).

**Comment by dogo** [comment]
What it's swift? this lib is objective-c

You can copy and paste my changes locally and test.
https://github.com/dogo/SCLAlertView/commit/6e3a4b2b0632ffcf63149107178890ff26d43835

**Comment by tlextrait** [comment]
Ah sorry I misunderstood, mis-read and thought you wanted me to look at the original code and see if it had the issue.

Your fix works perfectly thanks a lot!

**Comment by dogo** [comment]
@tlextrait Could you please test the version 0.4.3  I made some changes related to modal presentation.

**Comment by tlextrait** [comment]
Will do

-Thomas

**Comment by tlextrait** [comment]
Works great in 0.4.3
