### ISSUE TITLE
Device rotations support

### ISSUE THREAD

**Issue by yas375** [dogo/SCLAlertView#51]
Nice work!

I've just tried `0.4.2` version and looks like it doesn't handle nicely device rotations. Is it something expected at this point? Would be nice to support rotations.
Thanks in advance!

![2015-01-21_0105](https://cloud.githubusercontent.com/assets/217368/5827235/d2c30dc6-a109-11e4-8c8a-2832ce85e699.png)
![2015-01-21_01051](https://cloud.githubusercontent.com/assets/217368/5827234/d294ca88-a109-11e4-9dba-cdc86bd91fce.png)

**Comment by dogo** [comment]
I'm working on it, please use 0.4.0, until I fix the issue

**Comment by dogo** [comment]
Please update to 0.4.3

**Comment by yas375** [comment]
0.4.3 works well! Thanks for the quick fix :)
