### ISSUE TITLE
Keyboard & rotation

### ISSUE THREAD

**Issue by mythodeia** [dogo/SCLAlertView#52]
testing now on simulator for iPhone6.
Run demo app
Choose Show Edit
tap in the textfield. Keyboard appears and the control moves up.
Rotate simulator. The keyboard rotates and hides textfield.
Close the keyboard and you will see the control move downwards to compensate for the 
keyboard removal.

thanks for the control by the way :+1:

**Comment by dogo** [comment]
Thank you! Added to TODO

**Comment by mythodeia** [comment]
any updates on this?

**Comment by mythodeia** [comment]
closing this due to lack of response
