### ISSUE TITLE
ability to only show one alert

### ISSUE THREAD

**Issue by syrakozz** [dogo/SCLAlertView#56]
can you plz add a way or option to only show the alert one if there an alert appear, 
even if the user trigger an alert

**Comment by dogo** [comment]
What?

**Comment by syrakozz** [comment]
if the alert is showed, and we trigger another alert it will show above it, can you add an option to show only one alert at the time

**Comment by dogo** [comment]
This behaviour should be handled in the application side.

**Comment by syrakozz** [comment]
ok tx
