### ISSUE TITLE
SCLAlertView color

### ISSUE THREAD

**Issue by syrakozz** [dogo/SCLAlertView#57]
can i specify a uicolor for it, 
modifying the UIColor *viewColor; i mean

**Comment by dogo** [comment]
Please read the documentation and take a look on the example app  :D

```
[alert showCustom:self image:[UIImage imageNamed:@"git"] color:color title:@"Custom" subTitle:@"Add a custom icon and color for your own type of alert!" closeButtonTitle:@"OK" duration:0.0f]; 
````

**Comment by syrakozz** [comment]
aha, thank you :)

**Comment by syrakozz** [comment]
but when i user 
alert showEdit 
there is no color change ability

**Comment by dogo** [comment]
Please test the upstream code
```alert.customViewColor = [UIColor purpleColor];```

**Comment by dogo** [comment]
Please update to 0.5.3
