### ISSUE TITLE
textarea in alert

### ISSUE THREAD

**Issue by syrakozz** [dogo/SCLAlertView#61]
how i can add a textarea in the alert

**Comment by dogo** [comment]
The alert already have a text area.

**Comment by syrakozz** [comment]
i mean textview, an editeable one

**Comment by dogo** [comment]
No, you can't add another textView. The default alert is composed by : UILabel and a UITextView. 

You can add buttons and/or text fields

**Comment by syrakozz** [comment]
ah ok , thank you
