### ISSUE TITLE
Add custom view

### ISSUE THREAD

**Issue by guilhermearaujo** [dogo/SCLAlertView#62]
I would like to be able to add a custom view to the alert, or at least a subclass of `UITextField`.
Perhaps a method like `- (void)addTextField:(UITextField *)textField;`

**Comment by dogo** [comment]
```addTextField``` its not enough? 

You can customize laters using ```textField``` reference 

```
SCLAlertView *alert = [[SCLAlertView alloc] init];

UITextField *textField = [alert addTextField:@"Enter your name"];

[alert addButton:@"Show Name" actionBlock:^(void) {
    NSLog(@"Text value: %@", textField.text);
}];

[alert showEdit:self title:@"Edit View" subTitle:@"This alert view shows a text box" closeButtonTitle:@"Done" duration:0.0f];
```

**Comment by guilhermearaujo** [comment]
I am using a `UITextField` subclass that implements some input validation, and the only way to use to use it inside the alert is if I could add a previously created view. Since the method `addTextField:` automatically instantiates a regular `UITextField`, I can't replace it with the custom class I'm using. However, if I could pass a `UITextField`, I could pass the custom object.

**Comment by dogo** [comment]
Could you please test again, using commit f83a20b . 
Let me you if works as aspected

**Comment by guilhermearaujo** [comment]
Great, it works!

**Comment by dogo** [comment]
Official release 0.5.4

**Comment by mzekrallah** [comment]
Thank you guys but I guess having a custom view is also necessary not only text fields .. in my case I wanted to add a radio buttons group so having only text fields is kind of limiting. Please reconsider this. Thanks

**Comment by dogo** [comment]
Please @guilhermearaujo @mzekrallah update to 0.9.3
