### ISSUE TITLE
Blur backgroundtype is black

### ISSUE THREAD

**Issue by acenario** [dogo/SCLAlertView#63]
Hi,

I am deploying on iOS 7 and the blur background type is acting strangely. Any ideas?

![ios simulator screen shot feb 6 2015 9 22 17 pm](https://cloud.githubusercontent.com/assets/591849/6090409/516ab630-ae46-11e4-95ec-a58b9c29a7b7.png)

**Comment by dogo** [comment]
Hi @acenario.

It's running fine here iOS 7.1 iPhone 4S

![ios simulator screen shot feb 9 2015 2 09 01 pm](https://cloud.githubusercontent.com/assets/1487375/6109890/58944478-b065-11e4-9abf-0b0106c93c82.png)


Could you please give me more information :D

**Comment by dreampowder** [comment]
Hi diogo, i’ll test with the commit you’ve told and tell you the results soon. btw, heres what i get from the cocoapods version. 




In the screenshot, can you see the inception effect inside the “form” view?









İyi Çalışmalar, Serdar Coşkun.

**Comment by dogo** [comment]
Screenshot not found. 
           404 

hehe @dreampowder, please check your screenshot upload.

**Comment by dogo** [comment]
![ios simulator screen shot feb 9 2015 2 26 54 pm](https://cloud.githubusercontent.com/assets/1487375/6110274/d19402e4-b067-11e4-9963-ddbc69e809a0.png)

Yep, got it. Really funny inception

**Comment by dogo** [comment]
@dreampowder 

this is the expected behaviour  ?

https://dl.dropboxusercontent.com/u/12595498/blurModal.mov

**Comment by acenario** [comment]
@dogo I'm deploying iPhone 5S on 7.0. Here's the code that I use.

SCLAlertView *alertView = [[SCLAlertView alloc] init];
    alertView.backgroundType = Blur;
    alertView.customViewColor = [UIColor alizarinColor];
    alertView.showAnimationType = SlideInFromCenter;
    [alertView showWaiting:self title:@"Connecting" subTitle:@"Nobody understands the cloud..." closeButtonTitle:nil duration:0.0f];

**Comment by dogo** [comment]
@acenario, I tried your code and seems fine here. (iOS 7.1 and 8.1.3)
That's sad but I don't have any device with iOS 7.0, only with 7.1+

I will need you help to investigate this issue, could you please run the test app and check if occurs too.

![img_0287](https://cloud.githubusercontent.com/assets/1487375/6126314/7509c6b8-b106-11e4-93ff-eae84150440c.PNG)

**Comment by acenario** [comment]
Sorry, for the delay. Will help you investigate the issue soon.

**Comment by dogo** [comment]
No problem @acenario :D. Just for sanity check, test again with 0.5.7
