### ISSUE TITLE
Calling from inside a Model

### ISSUE THREAD

**Issue by gmogames** [dogo/SCLAlertView#64]
I have a custom Model that parses my JSON into properties and has a handleError method. Inside this handleError method I have an AlertView that popups the error to the user. Since this model is used everywhere, I wanted to replace the UIAlertview for the SCLAlertView, but it does require me to pass self or the viewcontroller, but inside the model, there is no self or viewcontroller.

What's the best option to make the SCLAlertview open from inside the Model?

THanks

**Comment by dogo** [comment]
Hi @gmogames you can use ```[[[UIApplication sharedApplication] keyWindow] rootViewController];``` as viewController
