### ISSUE TITLE
AlertView does not disable Interactive Pop Gesture

### ISSUE THREAD

**Issue by guilhermearaujo** [dogo/SCLAlertView#66]
When I show an alert which should not be cancellable by touching outside its view, I expect the user to be "blocked", restricted to one of the options I present him (using buttons in the alert).
I noticed, however, that if the alert is presented from a VC inside a UINavigationController, the pop gesture (swipe from left to go back) still works.

This is bad, in my case, for instance, because I show a Progress alert with a button to cancel the HTTP request I'm performing. If the view controller is dismissed prematurely, the request will still be processed in background, and its completion block will fail because the view controller is no longer available.

I suggest the interactive pop gesture to be disabled while the alert is visible.

**Comment by dogo** [comment]
Yep, @guilhermearaujo you are right, to disable the pop gesture I need access to the ```navigationController``` like this :+1: 
```<VIEWCONTROLLER>.navigationController.interactivePopGestureRecognizer.enabled = NO;```

The problem is: the viewController I get as a parameter can not have access to navigationController.
What we can do is: do a search looking for the navigationController or set it as an optional property

What you think about it?

**Comment by guilhermearaujo** [comment]
What about this?
```objc
UINavigationController *navController = [<#ViewController#> navigationController];
if (navController != nil) {
    [[navController interactivePopGestureRecognizer] setEnabled:NO];
}
```

Then set it back to enabled once the alert is dismissed.

**Comment by dogo** [comment]
@guilhermearaujo Yep, almost this.

Please test my fix 0ab2a30

**Comment by guilhermearaujo** [comment]
Your change will work if the view controller passed is embedded into a `UINavigationController`, however will still not work if the view controller *is* the `UINavigationController`.

**Comment by dogo** [comment]
Seems fine in all my tests, could you please provide me an sample?

**Comment by guilhermearaujo** [comment]
Here it goes: https://github.com/guilhermearaujo/SCLAlertView/commit/ff62b8cd21db1375ed06735bcd5f444c34e126ab

I've added a NavigationController and a previous view before your list of buttons to display the alerts.
Then I've changed the Error call to be presented on `[self navigationController]` instead of `self`.

Push any other button, and the swipe gesture is disabled. Push the error button and see what happens.

**Comment by dogo** [comment]
Patched :D
Please test c4ebc99 .

and thanks

**Comment by guilhermearaujo** [comment]
Perfect!

**Comment by dogo** [comment]
Official release 0.5.4
