### ISSUE TITLE
is it possible to add an icon to Button?

### ISSUE THREAD

**Issue by invisible66** [dogo/SCLAlertView#67]
How can i add an icon to Custom Button?

**Comment by dogo** [comment]
Like the regular way :  

```SCLButton *button = [alert addButton:@"First Button" target:self selector:@selector(firstButton)];
[button setBackgroundImage:[UIImage imageNamed:@"git"] forState:UIControlStateNormal];```

**Comment by invisible66** [comment]
I mean how can i add icon like this. :)

![ekran resmi 2015-02-13 15 19 39](https://cloud.githubusercontent.com/assets/8086679/6187837/1cfee094-b394-11e4-8e63-19828f98d7f1.png)

**Comment by dogo** [comment]
like the regular way too

button.imageEdgeInsets = UIEdgeInsetsMake(x, x, x, x);
button.titleEdgeInsets = UIEdgeInsetsMake(x, x, x, x);

**Comment by invisible66** [comment]
I got it. Thanks. :+1:
