### ISSUE TITLE
is it possible to add progress bar to Custom AlertView

### ISSUE THREAD

**Issue by invisible66** [dogo/SCLAlertView#68]
is it possible to add progress bar to Custom AlertView?

**Comment by dogo** [comment]
```showWaiting``` function uses UIActivityIndicatorView

**Comment by invisible66** [comment]
I am using `showWaiting` in my login screen. But i want to show a progress bar while user uploading files. i mean i want to show like this :
![ekran resmi 2015-02-13 15 32 57](https://cloud.githubusercontent.com/assets/8086679/6187986/a1619a2e-b395-11e4-9d77-1293287fe69a.png)

**Comment by dogo** [comment]
Nope, you can't add a custom view to SCAlertView

**Comment by invisible66** [comment]
It would be great i could add a custom view. Thanks for your quick answer.

**Comment by dogo** [comment]
This feature is not in my roadmap, but feel free to make a pull request supporting this

**Comment by invisible66** [comment]
i am beginner at IOS programming. I can't do this now. But in the future i'll do this :)

**Comment by dogo** [comment]
Good studies for you, I'm closing this error for now ok?

**Comment by invisible66** [comment]
Ok. Thanks again.
