### ISSUE TITLE
Execute block on dismissal

### ISSUE THREAD

**Issue by guilhermearaujo** [dogo/SCLAlertView#69]
It would be great if I could run some code after the alert is dismissed by pressing the Cancel button and tapping outside the view.

**Comment by dogo** [comment]
you can execute using :
//Receiving information that SCLAlertView is dismissed
[alert alertIsDismissed:^{
    NSLog(@"SCLAlertView dismissed!");
   //EXEC your code here
}];

**Comment by guilhermearaujo** [comment]
Exactly that! Sorry, I didn't see that method.
