### ISSUE TITLE
Custom button height feature request

### ISSUE THREAD

**Issue by anclefeudor** [dogo/SCLAlertView#71]
SUBJ! Button is too narrow for my fat fingers! ;)

**Comment by dogo** [comment]
@anclefeudor Please test my commit 2820f6fc1d10ccdbd61abc7b8a64d6d8e1f0c219

**Comment by dogo** [comment]
Update to 0.5.7

**Comment by accfews** [comment]
How to use this feature in current version, I just see constant MIN_HEIGHT, is there a way to override it when project is loaded via pod

**Comment by dogo** [comment]
```
SCLAlertView INIT

    SCLButton *button = [alertView addButton:@"Button"]

    CGRect frame = button.frame;
    frame.size.height = NEW_HEIGHT;
     button.frame = frame;

[alertView showAlert];
