### ISSUE TITLE
UIAppearance

### ISSUE THREAD

**Issue by guilhermearaujo** [dogo/SCLAlertView#72]
It would be great if the class implemented `UIAppearance`. This way we could set our default custom color and text font just once for every alert.

**Comment by dogo** [comment]
A PR to add this feature would be much appreciated.

**Comment by jflayhart** [comment]
Does something like this not do the job?
`alert.viewText.textColor = [UIColor whiteColor]; // subtitle text color`

**Comment by fabersky** [comment]
👍

**Comment by dogo** [comment]
@fabersky 
@jflayhart 
@guilhermearaujo 
I started to support ```UIAppearance```, currently SCLButton and SCLSwitchView supports UI_APPEARANCE_SELECTOR
