### ISSUE TITLE
Latest Version Fails To Build

### ISSUE THREAD

**Issue by Kfeavel** [dogo/SCLAlertView#74]
The current code is the following:

    if (SYSTEM_VERSION_LESS_THAN(@"8.0"))
        {
            // iOS versions before 7.0 did not switch the width and height on device roration
            if UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation])
            {
                CGSize ssz = sz;
                sz = CGSizeMake(ssz.height, ssz.width);
            }
        }
and it should be:

    if (SYSTEM_VERSION_LESS_THAN(@"8.0"))
        {
            // iOS versions before 7.0 did not switch the width and height on device roration
            if (UIInterfaceOrientationIsLandscape([[UIApplication sharedApplication] statusBarOrientation]))
            {
                CGSize ssz = sz;
                sz = CGSizeMake(ssz.height, ssz.width);
            }
        }

Xcode Version: 6.3
iOS Version: 8.3 Beta 1
Device: iPhone 5

**Comment by dogo** [comment]
Yep, the new Xcode beta complains about the missing parenthesis.

**Comment by dogo** [comment]
Please update to 0.5.6
