### ISSUE TITLE
Alert is behind the keyboard

### ISSUE THREAD

**Issue by EliasNaranjeeSani** [dogo/SCLAlertView#80]
Hi, 
First of all, thanks for this awesome tool.

How should I fix this when keyboard is showing?

![screen shot 2015-03-11 at 2 33 45 pm copy](https://cloud.githubusercontent.com/assets/4579208/6595127/7fba45da-c7fc-11e4-98f1-1b4bb5011612.png)

**Comment by dogo** [comment]
Hi, could you please post your alert code ?
It's a iPhone 4/4S ?

**Comment by EliasNaranjeeSani** [comment]
No its iPhone 6 runnig iOS 8.1
Keyboard is showing and then ask for an alert.

  SCLAlertView *alert=[[SCLAlertView alloc]init];
    alert.showAnimationType = SlideInToCenter;
    alert.backgroundType=Shadow;

    [alert showCustom:self
                image:[UIImage imageNamed:@"alertAvatar"] color:[UIColor colorWithRed:90/255.0 green:54/255.0 blue:44/255.0 alpha:1] title:@"test" subTitle:@"test" closeButtonTitle:@"Cancel" duration:0.0f];

**Comment by EliasNaranjeeSani** [comment]
Also I should add that my app is not optimized for iPhone 6 so its a scaled iPhone 5 app, running in iPhone 6 simulator.

**Comment by dogo** [comment]
Okay the trick should be done at developer side.

You have to add UIKeyboardWillShowNotification and UIKeyboardWillHideNotification observers like this:

``` Objective-c
- (void)addObservers
{
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillShow:) name:UIKeyboardWillShowNotification object:nil];
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillHide:) name:UIKeyboardWillHideNotification object:nil];
}

- (void)removeObservers
{
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIKeyboardWillShowNotification object:nil];
    [[NSNotificationCenter defaultCenter] removeObserver:self name:UIKeyboardWillHideNotification object:nil];
}

- (void)keyboardWillShow:(NSNotification *)notification
{
     //Move the alert view up
}

-(void)keyboardWillHide:(NSNotification *)notification
{
     //Move the alert view down or hide
}
```

**Comment by dogo** [comment]
owwww, the keyboard was visible before the alert, so you need to resignFirstResponder before show the alert

**Comment by EliasNaranjeeSani** [comment]
No it is not related to keyboardWillShow or willHide.
Keyboard is already in my view and then I ask SCLAlertView to come up. 

I think you should show SCLAlertView in a new Window but you don't. You are adding SCLAlertView as subview of a viewcontroller and it causes this problem. 
At least you should check that, if keyboard is showing in this view, the alert y position should be recalculated to be above the keyboard.

**Comment by EliasNaranjeeSani** [comment]
No I don't want to resign the textField and dismiss the keyboard. 

If the alert was in a new window we didn't had this problem now, agree?

**Comment by dogo** [comment]
yep, if the alert was in a new window the problem should not happens anymore, but it's not the case. I should make this change someday I'm kinda busy right now. You could make PR to add this feature, would be much appreciated.

**Comment by dogo** [comment]
@EliasNaranjeeSani Please take a look on this branch 
https://github.com/dogo/SCLAlertView/tree/feature/show-in-a-new-window

It's a initial work to support a new window, still have some issues to resolve but it is a start.

Let me know if its enough

**Comment by EliasNaranjeeSani** [comment]
@dogo : Sorry about my delay on this and really appreciate your work.
Seems the new branch is totally working now and presents the alerts in a new window. 
Will help you to make it more reliable on new branch if anything happened.

Again, thank you so much dude!

**Comment by EliasNaranjeeSani** [comment]
@dogo : I'm using showCustom method for showing an alert in new branch. It seems the transparent black background of alert is not animating smoothly. Where the problem comes from? Any idea on this?

**Comment by dogo** [comment]
Seems fine here

Iphone 6 Simulator
iOS 8.2

``` Objective-c
- (IBAction)showCustom:(id)sender
{
    SCLAlertView *alert = [[SCLAlertView alloc]init];
    alert.showAnimationType = SlideInToCenter;
    alert.backgroundType = Shadow;
    [alert showCustom:[UIImage imageNamed:@"git"] color:[UIColor colorWithRed:90/255.0 green:54/255.0 blue:44/255.0 alpha:1] title:@"test" subTitle:@"test" closeButtonTitle:@"Cancel" duration:0.0f];
}```

Could you please record a video ?

**Comment by EliasNaranjeeSani** [comment]
Oops! Found it was because of my HUD. I have HUD which hides before showing the alert and both of these have a transparent background. It causes a ripple when hiding HUD and showing the alert. 
Thank you @dogo .

**Comment by dogo** [comment]
@EliasNaranjeeSani Please update your branch with my recent changes and let me know if there is any problem. thanks

**Comment by EliasNaranjeeSani** [comment]
@dogo :+1: 
Updated. Seems I can not fit the icon in custom mode now. I was already fitting the icon using 
 self.circleIconHeight *= 3.0f;
but now it does not work.
![screen shot 2015-03-19 at 9 29 16 am](https://cloud.githubusercontent.com/assets/4579208/6725196/b5f25e52-ce1a-11e4-8aeb-41db4a76ba5f.png)
I wanna that icon be fitted in circle and its not possible now. Any idea on this?

**Comment by dogo** [comment]
Its my bad. I will fix this

**Comment by dogo** [comment]
Fixed update your branch

**Comment by EliasNaranjeeSani** [comment]
Updated. Everything seems working fine. Thanks a lot @dogo.

**Comment by dogo** [comment]
@EliasNaranjeeSani Please use master branch and init your alert using

```Objective-C
    SCLAlertView *alert = [[SCLAlertView alloc] initWithNewWindow];
    
    [alert addButton:@"Second Button" actionBlock:^(void) {
        NSLog(@"Second button tapped");
    }];
    
    [alert showSuccess:@"Title" subTitle:@"Subtitle" closeButtonTitle:@"ButtonTitle" duration:0.0f];
```

**Comment by dogo** [comment]
Please update to 0.7.0
