### ISSUE TITLE
SCLAlertView's button does not show up on iOS 7

### ISSUE THREAD

**Issue by wimbledon** [dogo/SCLAlertView#81]
In version 0.5.7, 
SCLAlertView's button does not show up on iOS 7.1.2 and the dismiss gestures does not work anymore...

**Comment by wimbledon** [comment]
I confirm that everything still works fine in version 0.5.6

**Comment by dogo** [comment]
Yep! If you need iOS 7.X support please use the 0.5.6 version. Until I fix

Thank you

**Comment by dogo** [comment]
Please update to SCLAlertView-Objective-C (0.5.8)

**Comment by russellquinn** [comment]
The button I add with addButton doesn't show up on iOS 8.2, with 0.5.8.

There's space made for it in the view, but no button.

**Comment by dogo** [comment]
Post your code please

**Comment by russellquinn** [comment]
[alert showError:self.mainNavigationController title:@"title" subTitle:@"subtitle" closeButtonTitle:@"text" duration:0.0f];

     SCLButton *yesButton = [alert addButton:@"text" actionBlock:^(void) {
         //my action
    }];

**Comment by dogo** [comment]
Weird seems fine here, but anyway I just release a new version. Please test with 0.5.9
