### ISSUE TITLE
Rotate - rotate on Ipad

### ISSUE THREAD

**Issue by lupugabriel** [dogo/SCLAlertView#82]
The white view changes it's height increasing his height at every rotate!
Is there a way to fix it?

**Comment by dogo** [comment]
Please revert to 0.5.6

**Comment by lupugabriel** [comment]
Wow! So quick. This is an awesome control. Do you need a screenshot? or you know about the bug?

**Comment by dogo** [comment]
hehehe thanks @lupugabriel It's a know issue =(

**Comment by lupugabriel** [comment]
pod 'SCLAlertView-Objective-C' , '~> 0.5.6' i tried like this but it's still installing 0.5.7

**Comment by lupugabriel** [comment]
pod 'SCLAlertView-Objective-C' , '0.5.6' it worked!

**Comment by lupugabriel** [comment]
it's still reproducing on 0.5.6 :(... same thing
![ios simulator screen shot 17 mar 2015 13 19 36](https://cloud.githubusercontent.com/assets/3657507/6688056/6230d0d2-cca8-11e4-97fa-151889f9a8ba.png)

**Comment by dogo** [comment]
Duh! 
Okay, lets gather some information : iOS version

**Comment by lupugabriel** [comment]
IOS 8.

SCLAlertView *alertView = [[SCLAlertView alloc] init];
    [alertView addButton:@"Rate it now!" actionBlock:^{
  
    }];
    [alertView addButton:@"Remind me later" actionBlock:^{
        
    }];
    [alertView addButton:@"No, thanks :(" actionBlock:^{
   
    }];
    
    [alertView showInfo:self title:nil subTitle:@"If you enjoy using Sell It, would you mind taking a moment to rate it?" closeButtonTitle:nil duration:0];

**Comment by lupugabriel** [comment]
and if i rotate a few times it incresease the height of the white view by a little bit

**Comment by dogo** [comment]
Please update to SCLAlertView-Objective-C (0.5.8)

**Comment by lupugabriel** [comment]
still occuring :(

**Comment by dogo** [comment]
Weird, It's running fine here take a look.

https://dl.dropboxusercontent.com/u/12595498/rotation_ipad.mov

Try to delete your pod folder and make a pod install again
