### ISSUE TITLE
new alert flick

### ISSUE THREAD

**Issue by syrakozz** [dogo/SCLAlertView#83]
its flick on the newest version

**Comment by syrakozz** [comment]
0.5.8 contain bug

**Comment by dogo** [comment]
Information about th issue please

**Comment by syrakozz** [comment]
its looks like it flick before than version , i just download 0.5.7
when you trigger an alert , the whole view go to the right about 0.5 second and then the alert appear, 
its like a flick

**Comment by syrakozz** [comment]
on version  0.5.6 its good ,
so the bug start  in 0.5.7

**Comment by dogo** [comment]
Seems fine here. Record a video please
