### ISSUE TITLE
Long texts truncated when using custom font

### ISSUE THREAD

**Issue by russellquinn** [dogo/SCLAlertView#84]
The solution to issue #38 doesn't seem to work if you use setBodyTextFontFamily.

**Comment by dogo** [comment]
Add to TODO: Fix ling texts with custom font

**Comment by dogo** [comment]
@russellquinn Could you please tell me which font and size

**Comment by russellquinn** [comment]
Sorry, I stopped using SCLAlert and this was a while back. I don't think I have a record anymore.

**Comment by dogo** [comment]
No problem @russellquinn thanks
