### ISSUE TITLE
shouldDismissOnTapOutside not working

### ISSUE THREAD

**Issue by chamira** [dogo/SCLAlertView#87]
When I set alert.shouldDismissOnTapOutside=true, it is not working as it supposed

I did some debugging and found out that you set the tapgesture recogniser to _backgroundView, which is actually lay behind self.view 

    [_rootViewController addChildViewController:self];
    [_rootViewController.view addSubview:_backgroundView];
    [_rootViewController.view addSubview:self.view];

Since self.view is the most top view _backgroundView does not recognise the tapgresture. therefore I added gesture recogniser to self.view and it works fine..  

- (void)setShouldDismissOnTapOutside:(BOOL)shouldDismissOnTapOutside
{
    _shouldDismissOnTapOutside = shouldDismissOnTapOutside;
    
    if(_shouldDismissOnTapOutside)
    {
        self.gestureRecognizer = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(handleTap:)];
        [self.view addGestureRecognizer:self.gestureRecognizer];
        
    }
}

**Comment by dogo** [comment]
Thanks for reporting, yeah I made some refactor a couple commits behind and introduced this issue. 

Please update to 0.6.1.
