### ISSUE TITLE
allow adding more controls

### ISSUE THREAD

**Issue by kalsky** [dogo/SCLAlertView#89]
today you can add only buttons and textfields.
I think some more controls could be used in such an alert like UIDatePicker, UIPickerView.
Also, to be more generic, I would also add an option to add a UIView - so everyone could add some custom UIs that they need there (for example a custom version of a date picker, calendar, list of switches, etc.)

Thanks!

**Comment by dogo** [comment]
Indeed currently it's not supported. A PR to add this feature would be much appreciated.

**Comment by kartikthapar** [comment]
I agree. Out of the ones listed in the OP, I consider adding a UIImageView to be the most crucial. This is not the same as the image in the top circle (as currently in my use case, I have disabled it in all my alerts).

**Comment by onewaterdrop** [comment]
+1. could you add some support to allow add some UIView like EDStarRating. thanks.

**Comment by DennisDreissen** [comment]
I would like to have the option for a datepicker too.

**Comment by mzekrallah** [comment]
+1 for custom UIView injection ...

**Comment by dogo** [comment]
@kalsky @kartikthapar @onewaterdrop @DennisDreissen @mzekrallah 

Please test the develop branch. :+1:

**Comment by dogo** [comment]
Please update to 0.9.2
