### ISSUE TITLE
addObservers for custom textfield

### ISSUE THREAD

**Issue by kartikthapar** [dogo/SCLAlertView#91]
I was just wondering if the exclusion of `addObservers` API call in `addCustomTextField:` was by design. Thanks!

**Comment by dogo** [comment]
Yes, It's by design since :D

**Comment by kartikthapar** [comment]
By design "since"? :)

**Comment by dogo** [comment]
hahahahaha forget the since :P. dead piece of text

**Comment by kartikthapar** [comment]
:)
