### ISSUE TITLE
SlideInFromCenter show animation with blur UI issue

### ISSUE THREAD

**Issue by kartikthapar** [dogo/SCLAlertView#92]
- (IBAction)showCustom:(id)sender
    {
        SCLAlertView *alert = [[SCLAlertView alloc] init];
        
        alert.backgroundType = Blur;
        alert.showAnimationType = SlideInFromCenter;
        
        UIColor *color = [UIColor colorWithRed:65.0/255.0 green:64.0/255.0 blue:144.0/255.0 alpha:1.0];
        [alert showCustom:self image:[UIImage imageNamed:@"git"] color:color title:@"Custom" subTitle:@"Add a custom icon and color for your own type of alert!" closeButtonTitle:@"OK" duration:0.0f];
    }

Results in:

![screen shot 2015-03-30 at 12 37 24 am](https://cloud.githubusercontent.com/assets/810861/6890236/34502f2e-d675-11e4-94ee-ea7f7e704e91.png)

**Comment by dogo** [comment]
Thank you for reporting.

**Comment by dogo** [comment]
Fixed. I will make a release soon

**Comment by dogo** [comment]
Please update to 0.7.0

**Comment by kartikthapar** [comment]
Thanks! :)
