### ISSUE TITLE
SCLAlertView width

### ISSUE THREAD

**Issue by kartikthapar** [dogo/SCLAlertView#94]
Currently as I see the width of the alert view is the same for all types of alerts. In some cases, I want my alert to be a bit wider than they are — consider the requirement of a UIActionSheet with a few buttons.

Is there a way I can just say — 

    alert.width = 300;

or something to that effect?

**Comment by dogo** [comment]
Sadly no =(, currently the alert with it's fixed. This feature is in my roadmap

**Comment by kartikthapar** [comment]
That's cool; is there a potential timeline for this?

**Comment by dogo** [comment]
hmm, is kinda hard to say because I don't have much time to spend this month. If I have to guess... maybe next month. Sorry

**Comment by kartikthapar** [comment]
No that's cool; no need to be sorry. Just making sure it doesn't conflict with my timeline or anything like that. Thanks!

**Comment by Supertecnoboff** [comment]
Yeah this would be a pretty awesome feature to add to the app.

**Comment by mzekrallah** [comment]
yes, it would be great to add this to feature .. Plus one :+1:

**Comment by dogo** [comment]
Currently working on "feature/custom-width" branch

**Comment by zhjuncai** [comment]
It would be great to have this feature

**Comment by dogo** [comment]
Please update 0.7.9 to custom width support
