### ISSUE TITLE
iOS edge swipe gesture

### ISSUE THREAD

**Issue by kartikthapar** [dogo/SCLAlertView#98]
I cannot say this with 100% assurance but it seems like the edge swipe gesture in a navigation controller is getting botched up because of the alert.

In a normal table view, my edge swipes work perfectly but after the alert is displayed, edge swipes become infrequent. Further edge swipes from particular points don't seem to work at all. I am not sure if this framework is the primary cause for this issue but it surely seems like it. Could someone else investigate? Thanks.w

**Comment by kartikthapar** [comment]
Hey @dogo, could you please verify this?

**Comment by dogo** [comment]
Hi, @kartikthapar 

Could you please provide me a example ? 

Just to make clear , when the SCLAlert shows up disableInteractivePopGesture is called and enableInteractivePopGesture is called at dealloc

**Comment by kartikthapar** [comment]
I have just been busy with a lot of stuff recently. I will be updating at this at point; hopefully with a sample project. Thanks for understanding.
