### ISSUE TITLE
Subtitle does not appear if title is set to nil or empty

### ISSUE THREAD

**Issue by guilhermearaujo** [dogo/SCLAlertView#99]
If `title` is set to `nil` or `@""`, then `subtitle` will not be visible. However, you can see the text if you scroll up. Looks like you're using a `UITextView`. Why not a simple `UILabel`?

![Image](http://cl.ly/image/0d083o372b33/Image%202015-04-08%20at%207.00.29%20PM.png)

**Comment by dogo** [comment]
![ios simulator screen shot apr 14 2015 5 21 07 pm](https://cloud.githubusercontent.com/assets/1487375/7146553/c40aad18-e2ca-11e4-8e8d-28f64ff4d908.png)

It's running fine here, are you using a custom font ?

**Comment by guilhermearaujo** [comment]
Yes, but in the button.
`pod 'SCLAlertView-Objective-C', '~> 0.7.0'`
```obj-c
NSString *errorMessage = @"Some message";

SCLAlertView *alertView = [SCLAlertView new];
[alertView setBackgroundType:Blur];
[alertView setCustomViewColor:[UIColor redColor]];
[alertView setButtonsTextFontFamily:@"HelveticaNeue-Light" withSize:15.0f];
[alertView showNotice:[self navigationController]
                title:NSLocalizedString(@"Opa!", @"Oops!")
             subTitle:errorMessage
     closeButtonTitle:NSLocalizedString(@"Fechar", @"Dismiss")
             duration:0];
```

**Comment by dogo** [comment]
Tested on:
iOS Simulator
iPhone 6 
iOS 8.1

My code : 

```Objective-C
    NSString *errorMessage = @"Para adicionar à lista de desejos é preciso fazer login";
    
    SCLAlertView *alertView = [SCLAlertView new];
    [alertView setBackgroundType:Blur];
    [alertView setCustomViewColor:[UIColor redColor]];
    [alertView setButtonsTextFontFamily:@"HelveticaNeue-Light" withSize:15.0f];
    [alertView showNotice:self
                    title:nil
                 subTitle:errorMessage
         closeButtonTitle:NSLocalizedString(@"Fechar", @"Dismiss")
                 duration:0];
```

![ios simulator screen shot apr 15 2015 9 50 59 am](https://cloud.githubusercontent.com/assets/1487375/7158961/3c6edd9e-e355-11e4-9009-67b5a658928a.png)

**Comment by guilhermearaujo** [comment]
Did you try using a navigation controller and calling `[alertView showNotice:[self navigationController] ...`?

**Comment by dogo** [comment]
Yep, @guilhermearaujo it's related with ```self navigationController``` =( 
Thanks

**Comment by dogo** [comment]
Please update to 0.8.0
